### ISSUE TITLE
Conflict with SBJson

### ISSUE THREAD

**Issue by thom-ek** [sumup/sumup-ios-sdk#1]
SumupSDK.framework uses `SBJson` internally. It conflicts when developer also uses `SBJson` in his project. SBJson framework usage should be prefixed to internal namespace like `SMPJson` to avoid conflicts. For example, DropboxSDK also uses SBJson as DBJson.

**Comment by mollidor** [comment]
Hi Tomasz.

Thanks for your feedback. We will look into this in an upcoming release.

Regards,
Lukas

**Comment by mollidor** [comment]
Hi Tomek.

Can you check if 1.2.1b1 fixes this issue?

Thanks,
Lukas

**Comment by thom-ek** [comment]
SBJson conflict is ok now, but now I've found another conflict on base64_encode with another lib which I use (fortunately I have source code for it and I change that function name). SDK is working now.

**Comment by mollidor** [comment]
Hi Tomek.

Glad to hear. Which base64 method is in conflict? Should be easy to fix on our side and will probably be in conflict for other devs, too.

**Comment by thom-ek** [comment]
It's base64_encode() :)

**Comment by mollidor** [comment]
We are using a copy of this category: https://github.com/l4u/NSData-Base64/blob/abeb10cfdbe5c2c3f16ed45f2a7f2b5094f097dd/NSData%2BBase64.m

Is this causing the conflict for you?

**Comment by thom-ek** [comment]
Yes, I used exactly same category, but this was very easy to fix at my side. Other conflict was with zbar and I had to recompile zbar.
