### ISSUE TITLE
`setupWithAPIKey` should handle error

### ISSUE THREAD

**Issue by alvaromb** [sumup/sumup-ios-sdk#10]
Docs about `setupWithAPIKey` says

```objc
/**
...
 \returns YES if setup was successful. NO otherwise or if SDK has been set up before.
...
 */
+ (BOOL)setupWithAPIKey:(NSString *)apiKey;
```

So one cannot distinguish if the setup wasn't successful or if the SDK has been set up before. This becomes a problem when developing a React Native app, because the app is being "refreshed", not recompiled, thus making impossible to know if there was an error or not.

Error handling should be done through an `NSError` pointer, and the `BOOL` can be left to know whether the SDK has been setup or not.

**Comment by mollidor** [comment]
Hi @alvaromb,

Thanks for getting in touch. We've already stumbled across the https://github.com/APSL/react-native-sumup repo. Nice. 

If set up before `+[SumupSDK setupWithAPIKey]` does indeed return `NO` as the method will refuse to do anything if it has been setup before. That said it doesn't "hurt" to call it multiple times. However I see your point, so providing better feedback might indeed be a nice addition to the current interface. However there are no meaningful errors to return by now. Unless you provide `nil` as the key the method will always succeed.

For the time being feel free to either keep track of the setup in your on (probably static) boolean or just call the method multiple times and just ignore the log.

Regards,
Lukas

**Comment by alvaromb** [comment]
Thanks @mollidor, just released a new version with some bugfixes and improvements. 

The thing is that I would like to do something if the setup fails (a logout from my backend, for instance) and do nothing if it has been previously set. With the actual behaviour I cannot do this because it will return `NO` in both cases. I've implemented a workaround so we can live with it, but it would be nice to distinguish an error from an "alive SDK session".

**Comment by mollidor** [comment]
Sure, I see the point. 

Once set up with your API key you will have an "alive SDK session". There is no need to set it up again. You can log out the current user by calling  `+logoutWithCompletionBlock:(SumupCompletionBlock)block;` and then log in a different user by calling

```
+ (void)presentLoginFromViewController:(UIViewController *)fromViewController
                              animated:(BOOL)animated
                       completionBlock:(SumupCompletionBlock)block;
```

There's no need to call `+[SumupSDK setupWithAPIKey]` more than once per app lifecycle as your app uses a single API key anyways.

**Comment by alvaromb** [comment]
In our use case it's not enough, we would really appreciate to being able to distinguish between an error and a previous SDK setup. We fetch the Sumup API key from an API call because each of the point of sales (PoS) app have a different configuration, and it's necessary to re-fetch PoS config each time a sale is completed as client requested to be that way.

**Comment by felixLam** [comment]
Does the API-Key change more than once? Is it originally unknown (nil) and is then fetched from the server? Or can one app session be used with multiple API keys?

**Comment by alvaromb** [comment]
We wait till' the key is fetched to setup the SDK. The client wants the app to be able to handle multiple keys, even if it's from the same session (if technically possible, of course).

**Comment by mollidor** [comment]
Hi @alvaromb 

Having multiple keys is not supported at the moment. A key is tight to a bundle identifier and there should be one key per bundle identifier only.

Can you please get in touch at integration@sumup.com so we can discuss your use case and possible solutions?

Regards,
Lukas

**Comment by alvaromb** [comment]
Thanks for the info @mollidor!

I'll check with our client if we can directly bundle the key instead of fetching from the API. If they absolutely need to stick with the actual behaviour we'll get in touch with you.

**Comment by mollidor** [comment]
Hi @alvaromb 

Did you manage to fulfil your client's requirements with the current SDK? Can we close this issue?

Regards,
Lukas

**Comment by alvaromb** [comment]
No more error 51, 50 or 21 Lukas!

Thanks for your support.
