### ISSUE TITLE
PresentLogin pops-view alignment issue in iPad

### ISSUE THREAD

**Issue by harifsp** [sumup/sumup-ios-sdk#102]
When present the "SumUpSDK.presentLogin" the popup like like double box & unwanted space displaying in top.
refer the screenshot
![Simulator Screen Shot - iPad Air (4th generation) - 2021-01-20 at 01 01 53](https://user-images.githubusercontent.com/30861420/105083922-9e878d80-5abb-11eb-9b6d-3ec3ce4d5996.png)
![Simulator Screen Shot - iPad Air (4th generation) - 2021-01-20 at 01 06 03](https://user-images.githubusercontent.com/30861420/105083992-bb23c580-5abb-11eb-8993-0dc7777e174e.png)

**Comment by sundusabrar-sumup** [comment]
hi @harifsp,

Can you please tell which version of iOS and Xcode are you using that brings up this issue?

Additionally, have you tried out our [sample app](https://github.com/sumup/sumup-ios-sdk/blob/master/SampleApp/SumUpSDKSampleApp/SrcSwift/AppDelegate.swift#L19-L23)?
