### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by philmartin83** [sumup/sumup-ios-sdk#103]
Hi, 

I'm trying to find out more information about the additionalInfo property for SMPCheckoutResult but this link is broken.

 http://docs.sumup.com/rest-api/transactions-api/

**Comment by andraskadar** [comment]
Hi @philmartin83!

Sorry for the inconvenience, the link to the API was not updated in the source code, but you can find the correct links in the [README](https://github.com/sumup/sumup-ios-sdk/blob/master/README.md), we will fix it for the next version.

Can you try this? https://developer.sumup.com/rest-api/#tag/Transactions
