### ISSUE TITLE
SDSStyleSheet console logging on Xcode 13 beta

### ISSUE THREAD

**Issue by sammcewan** [sumup/sumup-ios-sdk#109]
Very early heads up that the SDK is throwing this log to our console when running Xcode 13 beta / iOS 15.

```
+[SDSStyleSheet styleSheetFromURL:] (line 179): Could not load style sheet data from URL: (null)
```

**Comment by sammcewan** [comment]
This is now in RC and the issue remains.

**Comment by vx8** [comment]
Can we have an update on this? 
We are also facing the same issue.

Thanks

**Comment by breitung** [comment]
Having the same problem.

**Comment by Ceroce** [comment]
Still not fixed in release 4.2 of the SDK 😤

**Comment by ls-philippe-casgrain** [comment]
Also getting this issue, and it's worse with SwiftUI views for some reason.

**Comment by cwimberger** [comment]
Never thought that this would be necessary, but enough is enough. Here is a gist to silence this log message while we wait for a fix:

https://gist.github.com/cwimberger/9089354f12e7f60fea201a65e99a86fa
