### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by philmartin83** [sumup/sumup-ios-sdk#110]
I'm trying to investigate an error code but this link is broken
https://github.com/sumup/sumup-ios-sdk/blob/master/SumUpSDK.xcframework/ios-armv7_arm64/SumUpSDK.framework/Headers/SMPSumUpSDK.h#L155

the error code is com.sumup.sdk.error 51 (If anyone wants to help with what that error code is that would be helpful)

**Comment by floschliep** [comment]
Hi @philmartin83 - I believe this is the correct link: https://github.com/sumup/sumup-ios-sdk/blob/master/SumUpSDK.xcframework/ios-i386_x86_64-simulator/SumUpSDK.framework/Headers/SMPSumUpSDK.h#L169
You can find our all our error code definitions in that file.

**Comment by philmartin83** [comment]
Thats great thanks for your help
