### ISSUE TITLE
payment link at checkout

### ISSUE THREAD

**Issue by raphaels17** [sumup/sumup-ios-sdk#127]
Hi 

I have a payment link at checkout at a customer(photo). They want to get rid if this how do I proceed ?
 Here is the snippet of code 
```

 let request = CheckoutRequest(total: total,
                                         title: String(describing: total),
                                         currencyCode: merchantCurrencyCode,
                                         paymentOptions: [.cardReader, .mobilePayment])
```

![IMG_0111](https://github.com/sumup/sumup-ios-sdk/assets/3678600/bc0ea307-bdcb-4cf9-b59c-96aac5d96bd4)

 on a another note I am struggling to acquire payment scope activated for transparent login. Can someone help ?

**Comment by jadeburton-sumup** [comment]
Hi [raphaels17](https://github.com/raphaels17), which version of the SDK is this?

**Comment by raphaels17** [comment]
Hi @jadeburton-sumup 


I use   - SumUpSDK (4.2.0)

**Comment by jadeburton-sumup** [comment]
4.2 still supports Payment Links as a payment method, so it can indeed appear.  You can hide it by changing the merchant's configuration, which affects both the app and SDK.  The merchant needs to go into the regular SumUp app, log in if not already, turn off the Payment Links payment method (Payment Links on home screen | cog icon in top right corner.)

**Comment by raphaels17** [comment]
Thanks a lot. That part worked. 

ps : would still appreciate to know how to acquire transparent login, we have a dev test account, I don't now how to get this there or later for the customers.

**Comment by raphaels17** [comment]
I mean have the payment scope so that the app does request login and password on  a recurring basis.
The goes through chat support but I haven't got any help so far
