### ISSUE TITLE
Not Loaded

### ISSUE THREAD

**Issue by dipsvaishnav** [sumup/sumup-ios-sdk#13]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/Admin/Library/Developer/CoreSimulator/Devices/3AFB09B3-0750-4535-A92F-*************C/data/Containers/Bundle/Application/227D8BCB-55A9-4BE3-B192-72DB618477BA/SumUp.app> (loaded)' with name 'PECLoginSharedVC''

**Comment by mollidor** [comment]
Hi @dipsvaishnav .

Please make sure the bundles provided with the SDK are added to your target correctly. See https://github.com/sumup/sumup-ios-sdk#preparing-your-xcode-project for details. It seems the `SMPSharedResources.bundle` is not part of your app's "Copy Resources" phase.

Regards,
Lukas

**Comment by dipsvaishnav** [comment]
Tnx it's working i use simulator it's working ya not

Deepak Kumar Vaishnav

**Comment by mollidor** [comment]
Hi @dipsvaishnav . 

Is it working as expected? If so, can we close the issue? 

Thanks,
Lukas

**Comment by dipsvaishnav** [comment]
Need to any hardware attach compulsory

Deepak Kumar Vaishnav
