### ISSUE TITLE
Support for Tap on phone

### ISSUE THREAD

**Issue by flipbosch** [sumup/sumup-ios-sdk#132]
Since Apple did role out "Tap on phone" and it's now available in the Sumup App itself. It should be nice if we can also make it available in the SDK. Or is this not allowed for the Apple Guidelines?  

This will convert all iPhones to terminals, what should be very useful for all of us!

**Comment by tommyvkessel** [comment]
This would be great!

**Comment by Docgg** [comment]
yes...This would be great!

**Comment by oliverschaefer** [comment]
@jadeburton-sumup Since Tap to Pay is rolling out to more and more countries (Germany since today), are there any plans to support this in the near future?

**Comment by oliverschaefer** [comment]
@jadeburton-sumup Perfect thanks, please update this issue once something becomes available

**Comment by annaafanasyeva-sumup** [comment]
Hi folks, we have released the new [iOS SDK v.6.0.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v6.0.0) with Tap to Pay on iPhone support! Please refer to the [integration documentation](https://github.com/sumup/sumup-ios-sdk/blob/v6.0.0/README.md#tap-to-pay-on-iphone)!
