### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by ls-philipp-jacob** [sumup/sumup-ios-sdk#139]
Is there any plan to release a new version of the SumUp iOS SDK that includes a `PrivacyInfo.xcprivacy` manifest file any time soon, i.e. before Apple's deadline (soft: March 13, 2024; hard: May 1, 2024)?

See here for the announcement: https://developer.apple.com/news/?id=3d8a9yyh
See here for details: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by annaafanasyeva-sumup** [comment]
Hi @ls-philipp-jacob , thank you for bringing it up! We are currently working on it and we will get back to you when the new SDK version is available.

**Comment by annaafanasyeva-sumup** [comment]
Hi @ls-philipp-jacob ! The new SumUpSDK [4.4.1](https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.4.1) now includes the Privacy Manifest file! Please check it out!
