### ISSUE TITLE
Sumup ios SDK issue -[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance 0x15f623b50

### ISSUE THREAD

**Issue by test8git** [sumup/sumup-ios-sdk#14]
Hi,

we are receiving this issue when we want to build the project:
-[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance 0x15f623b50
2015-12-08 16:34:32.408 POS[2873:762491] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance 0x15f623b50'

we are not using storboard.

and we try your given solution -force_load/-all_load with path of sdk but these are giving linker error.

**Comment by mollidor** [comment]
Hi @test8git ,

you'll need the `-force_load` option unfortunately. What linker warning are you getting?

Can you give the current 1.3 beta a try and see if it solves the issue? It's available on develop. https://github.com/sumup/sumup-ios-sdk/tree/develop
