### ISSUE TITLE
Solo Lite does not connect to SDK 4.4.1

### ISSUE THREAD

**Issue by luukjansen** [sumup/sumup-ios-sdk#140]
The Sumup Air is not available anymore, and seems to be replaced by the Solo Lite.
The Solo Lite however does not show up when trying to connect to a device using the SDK. I tried on two different devices, and  both don't show it. I also installed the Sumup App on one of the devices, and connectivity work correctly, so it doesn't seem to be a hardware issue.

I there something specific I need to do to get the Sumup Lite to work with the latest version of the Sumup iOS SDK?

**Comment by jadeburton-sumup** [comment]
> Air ... seems to be replaced by the Solo Lite

Hi @luukjansen, I didn't understand what you meant here, can you please elaborate?

> I there something specific I need to do to get the Sumup Lite to work with the latest version of the Sumup iOS SDK?

The SDK currently doesn't support the Solo Lite.

**Comment by luukjansen** [comment]
That explains the issue. Is there a timeframe in which it will be?
Unless the Air is still available through other channels it means we can't get a compatible reader for any new installations of our payment solution.

**Comment by jadeburton-sumup** [comment]
We are currently working on a new version of the SDK that among others will add support for the Solo Lite card reader. It will be released within the next few weeks.
Thank you for the feedback.

**Comment by luukjansen** [comment]
Great, thank you!

I bought a few Air ones at a local retailer so will be ok to bridge the time until the SDK is ready.

Luuk

**Comment by annaafanasyeva-sumup** [comment]
Hi @luukjansen ! Please check out SumUp iOS SDK 5.0.0 which among other new features and improvements includes support for the Solo Lite card reader!
