### ISSUE TITLE
Tap to Pay on iPhone

### ISSUE THREAD

**Issue by jannis6023** [sumup/sumup-ios-sdk#148]
Tap to pay on iPhone isn’t shown as a payment method, even if there is an active & valid tap to pay entitlement!

**Comment by jadeburton-sumup** [comment]
> Tap to pay on iPhone isn’t shown as a payment method

The sample app does not yet have a button to start a Tap to Pay checkout. We will add this in a future release.

Or do you mean the method that detects if the feature is available/activated (`checkTapToPayAvailability:`) is returning `isActivated` false or `isAvailable` false?

**Comment by jannis6023** [comment]
No, I meant the implementation using Deep linking to the SumUp App.But the other way: is tap to pay already implemented in this SDK? Then this may be the way better alternative…Am 01.08.2024 um 10:20 schrieb Jade Burton ***@***.***>:﻿

Tap to pay on iPhone isn’t shown as a payment method

The sample app does not yet have a button to start a Tap to Pay checkout. We will add this in a future release.
Or do you mean the method that detects if the feature is available/activated (checkTapToPayAvailability:) is returning isActivated false or isAvailable false?

**Comment by jadeburton-sumup** [comment]
Yes it's available in the SDK! Please have a look at [the section in the readme](https://github.com/sumup/sumup-ios-sdk?tab=readme-ov-file#tap-to-pay-on-iphone)
