### ISSUE TITLE
SSKeychain class in SumUp SDK breaks iOS 10

### ISSUE THREAD

**Issue by dclerc** [sumup/sumup-ios-sdk#15]
Hi,

Apparently SumUp's SDK declares a class called SSKeychain which is in conflict with the system one. This is causing us issues with key chain functions (i.e. our app doesn't work when compiled for iOS 10).

Could you remove this class from your SDK ?

objc[67397]: Class SSKeychain is implemented in both /Users/xx/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreServices.framework/StoreServices (0x11752d490) and /Users/xx/Library/Developer/CoreSimulator/Devices/169BEXXX-11CC-41B7-AAD7-86A3A2C9B58E/data/Containers/Bundle/Application/E8F77XXX-4EEC-4D4F-B9B9-A6E7EB75C85E/xx.app/xxApp (0x1060ecf00). One of the two will be used. Which one is undefined.

**Comment by mollidor** [comment]
thanks for the report. We'll look into it.

**Comment by mollidor** [comment]
Hi @dclerc .

We've just released 1.3.0b4 which hopefully fixes your issue. Would you mind giving it a try and let us know? https://github.com/sumup/sumup-ios-sdk/tree/develop

Thanks,
Lukas

**Comment by dclerc** [comment]
It works, thanks!

**Comment by mollidor** [comment]
Thanks for raising it. Please keep in mind to add `NSBluetoothPeripheralUsageDescription` to your info plist when building on iOS 10 as it will crash if not present and firing up BTLE.

See https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW20
