### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by asa47** [sumup/sumup-ios-sdk#16]
Hello, I am having an issue with the login process.
After calling the `[SumupSDK presentLoginFromViewController:self.viewController animated:YES completionBlock:nil];` it shows the login view but the login fails all the times, displaying the following message:  
> Server Error: These login details are not valid. Please check your username and password and try again.

I used the same login details with your sample app, and it works. Right now I am not sure, why it works with your sample app, but it does not work within our app, so I am assuming that I am doing something wrong or that I am missing something.... any advice?

**Comment by mollidor** [comment]
Hi @asa47 .

You will have to create an SDK key that is connected to your app's bundle identifier. The sample app uses a pre-configured key that has been setup before. Please see https://sumup.com/integration#transactionReportingAPIs and https://me.sumup.com/developers

Make sure to provide your bundle identifier as the "New application ID"

Regards,
Lukas

**Comment by asa47** [comment]
Thanks for the quick reply @mollidor! And we have already connected the API Key with our app's bundle identifier, however the issue persists. Do you know if the issue can be caused by something else?

**Comment by mollidor** [comment]
Tricky to say. Can you take a look at the error that's returned? And its underlying error if present?

**Comment by mollidor** [comment]
If the problem persist please get in touch at integration@sumup.com and we'll figure it out together.

**Comment by mollidor** [comment]
Hi @asa47 

Has your problem been solved? Don't hesitate to get in touch via email if the issue persists.

Regards,
Lukas

**Comment by asa47** [comment]
Thanks, I will send an email to the support.

**Comment by mollidor** [comment]
Happy we could help. Will close this now. Feel free to get in touch anytime.

**Comment by raghubb4444** [comment]
I am not able to do login. Just i added sumup sdk into my app. What are all the things i have to update?

Server Error: These login details are not valid. Please check your username and password and try again.

**Comment by raghubb4444** [comment]
I created account in sumup and copied sumup sdk code into my account.Please provide steps to proceed.

**Comment by felixLam** [comment]
Hi @raghubb4444,

have you created an SDK Key as described here:
> You will have to create an SDK key that is connected to your app's bundle identifier. The sample app uses a pre-configured key that has been setup before. Please see https://sumup.com/integration#transactionReportingAPIs and https://me.sumup.com/developers

> Make sure to provide your bundle identifier as the "New application ID"

Kind regards,

Felix

**Comment by raghubb4444** [comment]
Ya got my key. And I gave that key to my code.But now if i click charge button am not able to show device screen.Please help out. i ill be stuck with this issue for t past one day.

**Comment by raghubb4444** [comment]
I am getting error code 20....There is a problem with version . How to solve this?
If i call SumupSDK.bundleVersionShortString()...It shows empty...Whats the problem?Please do reply

**Comment by raghubb4444** [comment]
I integrated version 2.2 as i was using xcode 7.3... Thats the problem in version i think....Now i am getting this error : duplicate symbol _FMDBBlockSQLiteCallBackFunction in:
    /Users/vertace/Library/Developer/Xcode/DerivedData/payableApp-cwmqestxrnxznvgmbkvctycwuexq/Build/Intermediates/payableApp.build/Debug-iphonesimulator/payableApp.build/Objects-normal/i386/FMDatabase.o
    /Users/vertace/Desktop/Cpp Sumup sample update sdk/SumupSDK.embeddedframework/SumupSDK.framework/SumupSDK(ADYFMDatabase.o)
ld: 1 duplicate symbol for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am using FMDatabase in my project...
Please provide solution for this.

**Comment by mollidor** [comment]
Hi.

We are not aware of any problems using version 2.3 on Xcode 7.3. Please give 2.3 another try.
If the version is reported as nil you might have missed adding the bundles to your target. Please see https://github.com/sumup/sumup-ios-sdk#preparing-your-xcode-project (Step 5 specifically) and call `+[SumupSDK testSDKIntegration]`. It should highlight things you might have missed.

Regards,
Lukas

**Comment by jjromannet** [comment]
Hello, 
I was getting the same problem with login - I am using Android SDK, 
In my case the problem was that Application ID set up in dashboard needs to  be the same as package name in your java code - this i was missing from spec - first few times i read it.

> Application Identifier that is equivalent to your package name or bundle ID in the com.example.app format.

When i set up application id correctly in dashboard - everything started to work.

Regards,
Jan
