### ISSUE TITLE
SumupSDK.bundleVersionShortString(), SumupSDK.bundleVersion() == NULL

### ISSUE THREAD

**Issue by luka1995** [sumup/sumup-ios-sdk#17]
I have problem that versions are empty.

Can you check?

**Comment by mollidor** [comment]
Is this fixed as well when you import the bundle in #18 ?

Am Samstag, 8. Oktober 2016 schrieb Luka Penger :

**Comment by luka1995** [comment]
Yea now is fixed. Do not forget to import bundle in target.

Do you have any example of output for  checkoutResult?.additionalInfo ?

**Comment by mollidor** [comment]
Hi @luka1995 .

Sorry, I somehow missed your question. Fee free to get in touch at integration@sumup.com if you need help.
