### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by thom-ek** [sumup/sumup-ios-sdk#19]
Please, register sumup-ios-sdk project in CocoaPods. This will help to keep SDK up to date in our projects.

**Comment by raphaels17** [comment]
we agree it is not in there yet right?

**Comment by mollidor** [comment]
Correct. Not supported at the moment.

**Comment by thom-ek** [comment]
When you plan to add this? This is very easy to implement. I've made pod for this locally in just few minutes, but local pod does not solve problem.

**Comment by shagedorn** [comment]
We are currently working on it.

**Comment by raphaels17** [comment]
Hi

I think I found part of the issue and have been able to reproduce it .
When Adding the SDK , my version of XCode  added the project as a target
for the SDK.
Unckecking the project for the bundle file and SDK seem to have remove some
of error message.
I still have SumupSDK.framework: bundle format unrecognized, invalid, or
unsuitable

Command /usr/bin/codesign failed with exit code 1


2017-03-03 9:17 GMT+01:00 Hagi <notifications@github.com>:

**Comment by Isabellle** [comment]
Any update on this?

**Comment by kkizlaitis** [comment]
Since this issue is not solved yet, @thom-ek , could you elaborate on how you created a pod locally? What is your `.podspec`? Any help would be greatly appreciated!

**Comment by shagedorn** [comment]
We have just released the SumUpSDK 3.0 beta 1, which among many other improvements, includes support for CocoaPods.

https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.0b1

Version 3.0 includes a couple of source-breaking changes. While all of them should be trivial to fix (if not, please let us know), we encourage you to read the [migration guide](https://github.com/sumup/sumup-ios-sdk/blob/develop/CHANGELOG.md) carefully.

We hope the Pods support works as expected. Thanks for your patience.

**Comment by shagedorn** [comment]
Sorry for the long wait, but not [v3.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.0) is officially out, including CocoaPods support.
