### ISSUE TITLE
Insufficient transaction information

### ISSUE THREAD

**Issue by thom-ek** [sumup/sumup-ios-sdk#2]
I would like to print payment confirmation for customer, but SMPCheckoutResult has only transactionCode. There should be also: card type (VISA, MasterCard, etc), card expiration (yy/mm), masked card number (last 4 digits), merchant name, terminal id, exact transaction timestamp, card issuer identification.

**Comment by thom-ek** [comment]
Yes, probably I can query with JSON API, but then I have to login twice - first at `+presentLoginFromViewController:animated:completionBlock:` and second somewhere in my interface. This will look bad. So, I'm waiting for detailed `SMPCheckoutResult`.

**Comment by mollidor** [comment]
Will let you know when we have something to try in a beta build. Thanks for bringing this up.
