### ISSUE TITLE
Connecting to the sum up reader Air (AIRE000)

### ISSUE THREAD

**Issue by asa47** [sumup/sumup-ios-sdk#20]
Hello, 
Is it possible to connect to the new Air reader? 
When we try to connect to a reader, it always looks for the pin+ devices, but we would like to use the new model. Any advice?

Thanks

**Comment by konradfeketesumup** [comment]
Hi asa47,
Please find our SDK version in Beta, including AIR support [here](https://github.com/sumup/sumup-ios-sdk/tree/develop).
Let us know how this works for you, any feedback would be much appreciated.
Best regards
Konrad

**Comment by asa47** [comment]
Hello, I tested the new beta SDK, and we managed to connect with the sumUp reader Air. Thanks!
Additionally I would like to know if you could add additional features to the current SDK.

- Currently once the payment screen appear (checkout page), there is no way to cancel/close the page, we have to manually insert a card and cancel, or wait for the timeout function. Could you add a button to allow the user to close the page?

- The SumUp reader seem to be a bit slow, would it be possible to update the firmware of the device?

- Would it be possible to hide the send receipt features?

Please let me know, and thanks again for the support! :)

**Comment by mollidor** [comment]
@asa47 

Hi there.

* early on in the checkout process there should be a cancel button top left. As soon as the transaction is in progress cancellation is handled by the reader only. Once you've read a card and don't want to proceed you should be able to tap the red x on the reader and cancel the transactions. There are scenarios where cancellation is not straight forward and we'll try to resolve these in upcoming versions.

* Transaction speed depends on a whole lot of different factors. Network latency being one of them. You can try to re-run the reader setup and see if there's a firmware update available.

* This will be configurable in an upcoming SDK version. If you happen to have more specific requirements feel free to get in touch at integration@sumup.com
