### ISSUE TITLE
API Key Issue

### ISSUE THREAD

**Issue by raghubb4444** [sumup/sumup-ios-sdk#21]
You have mentioned that, you have to use your own API key to access sumup sdk methods. How to get my API key? Please help out.

**Comment by konradfeketesumup** [comment]
Hi,

Please create a SumUp merchant account and login to your [Dashboard](https://me.sumup.com/login). In the footer under ”Developers” you will be able to request the relevant Key by providing your application identifier.
Best

**Comment by vitalii-tym** [comment]
To whoever who is lost in finding the API key (like I was), current its location is:
(1) open account settings > For developers > Toolkit  - it is going to open a separate page
(2) that page is just a marketing linking to SDKs and other, but after you click "Login" it will unhide the "Account" menu nearby
(3) hover over the Account menu and you will find the link to "API Keys" section there.
