### ISSUE TITLE
Device Screen

### ISSUE THREAD

**Issue by raghubb4444** [sumup/sumup-ios-sdk#22]
After clicking Charge, am not able to present that device showing screen.It doesn't error but its not showing device screen

**Comment by felixLam** [comment]
Hi @raghubb4444,

could you provide a bit more detail. Could you post a section of your code of how you setup the SDK (excluding confidential information such as your API key) and how you trigger the transaction?

Kind regards,

Felix

**Comment by raghubb4444** [comment]
sumupsdk Which was downloaded from Github was working.But now i took the key from my sumup login by adding my bundle identifier. Then if i click the charge button am not able to show the Device screen. In chargeButtonAction there is no presenting of new view but how the device screen appears. Am having a chargeButton while clicking i have to show device screen.

**Comment by raghubb4444** [comment]
Here i have added my code. Please go Through and provide solution.I added the sumSdk and Api Key into my code.
https://gist.github.com/raghubb4444/8c9b5fea21c718298eba0c4f3d392ef6

**Comment by felixLam** [comment]
You only handle one error explicitly. You also force unwrap the error, which is unsafe as it might well be nil (in the success case). Given that you don't report a crash, there probably is an error there. 

Have you tried logging all errors:

```swift
SumupSDK.checkoutWithRequest(request, fromViewController: self) { [weak self] (result: SMPCheckoutResult?, error: NSError?) -> Void	 in
    if let safeError = error {
        print("error during checkout: \(safeError)")
        if (safeError.domain == SMPSumupSDKErrorDomain) && (safeError.code == SMPSumupSDKError.accountNotLoggedIn) {
            self?.showResultsString("not logged in")
        }
        return;
    }

    guard let safeResult = result else {
        print("no error and no result should not happen");
        return;
    }

    print("result_transaction==\(safeResult.transactionCode)")
    self?.showResultsString("\(safeResult.success ? "Thank you" : "No charge") - \(safeResult.transactionCode)")
    if safeResult.success {
        print("success")
    }
}
```

You should also not use the magic number `21` and use the enum defined for that error (as this may change in later releases): `SMPSumupSDKErrorAccountNotLoggedIn` (depending on your swift version `SMPSumupSDKError.accountNotLoggedIn` might be Title-cased). Using the appropriate constants ensures that changes to the SDK are automatically propagated to your code.

You also should probably also use weak self inside the completion block (unless you want the SDK to retain the calling view controller).

Please take the above code snippet with a grain of salt as I have written it without a swift project or IDE.

**Comment by raghubb4444** [comment]
if i put SMPSumupSDKError.AccountNotLoggedIn, it shows Error 

issue: Cannot invoke initializer for type 'Int' with an argument list of type '(SMPSumupSDKError)'

**Comment by raghubb4444** [comment]
i want to present the view (which shows Device Hardware). How to do that?

**Comment by felixLam** [comment]
I forgot to append .rawValue:

```swift
        if (safeError.domain == SMPSumupSDKErrorDomain) && (safeError.code == SMPSumupSDKError.accountNotLoggedIn.rawValue) {
```

Could you please post the log that you see when running the above completion block?

Please understand that the call `SumupSDK.checkoutWithRequest` is asynchronous (hence the completion block). So the line afterwards is executing before the completion block.

**Comment by raghubb4444** [comment]
2016-11-04 17:48:06.986 payableApp[698:266841] SumupSDK: Not presenting checkout as user is not logged in.error during checkout: Error Domain=SumupSDKError Code=21 "(null)"2016-11-04 17:48:09.726:  Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"

**Comment by felixLam** [comment]
Did you login the user before allowing the user to tap the charge button?

see `presentLoginFromViewController`

**Comment by raghubb4444** [comment]
yes after login only am clicking Charge Button.It allows my login credentials

**Comment by raghubb4444** [comment]
Ok.I copied Library Objective-c code into my app, its running.But i have to change the Total Charge Amount ($10.00).How to do that?how to change the TotalCharge Amount?

**Comment by felixLam** [comment]
You create the request in your code from a string `total`. It is important to use an `NSDecimalNumber` and not an `NSNumber` when creating the `SMPCheckoutRequest`. Ideally you use a string for that e.g. `NSDecimalNumber(string: "11.50")`:
```swift
let totalString = "11.50"
let totalAmount = NSDecimalNumber(string: totalString)
let request = SMPCheckoutRequest(total: totalAmount, title: Appconstant.dollar, currencyCode: currencyCode, paymentOptions: SMPPaymentOptions.Any)
```

**Comment by felixLam** [comment]
@raghubb4444 The initial issue seems to be resolved correct?

**Comment by raghubb4444** [comment]
Am not asking that.jus am sending currencyCode =@"USD".But it shows EUR. How to change that?

**Comment by felixLam** [comment]
The currencyCode should match the merchant's currency. See the demo app: `[[SumupSDK currentMerchant] currencyCode];`

**Comment by raghubb4444** [comment]
How to change the merchants currency. I need to charge the amount in dollar

**Comment by felixLam** [comment]
The merchant's currency depends on his or her country of residence and can not be change as far as I know.

**Comment by felixLam** [comment]
Feel free to open a new issue if you have another question than the original one.

**Comment by pradeepkumari** [comment]
Hi are you there?

**Comment by felixLam** [comment]
@raghubb4444 I have updated the code snippet above for Swift 3 where the Error handling is slightly different.
