### ISSUE TITLE
BUG: Not able to cancel payment

### ISSUE THREAD

**Issue by thom-ek** [sumup/sumup-ios-sdk#23]
When I call [SumupSDK checkoutWithRequest:fromViewController:completion:] presented view controlled sometimes doesn't have Cancel button - same problem exists on original Sumup.app. Only one way to cancel payment is to kill an app.

**Comment by felixLam** [comment]
Could you post a screenshot?

**Comment by felixLam** [comment]
May this be related to https://github.com/sumup/sumup-ios-sdk/issues/6

**Comment by thom-ek** [comment]
Yes, it's the same problem. But I think that sometimes I saw Cancel button... I'll try to check more deeply when it is displayed.

**Comment by felixLam** [comment]
Can I close this issue as a duplicate and we follow up under the discussion on #6?

**Comment by thom-ek** [comment]
Yes
