### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by pradeepkumari** [sumup/sumup-ios-sdk#26]
Issue : Not presenting checkout as user is not logged in. But am able to login

**Comment by mollidor** [comment]
So you
* call `presentLoginFromViewController:...` 
* completion block indicates a successful login
* `+[SumupSDK currentMerchant]` returns a valid merchant

and then `+ [SumupSDK checkoutWithRequest:fromViewController:completion:]` comes back with an error indicating there's no merchant logged in?

**Comment by pradeepkumari** [comment]
I wrote my code in swift. Now am not able to login...What should i do?

**Comment by pradeepkumari** [comment]
Pls Helpout i need swift code for login action...

**Comment by felixLam** [comment]
Hi @pradeepkumari could you please post a gist with the code you have so far (excluding sensitive API keys and other info)?

**Comment by pradeepkumari** [comment]
Hi @felixLam  i imported objective c sumup sdk in my swift project. now i am not able to write login action action...how to write?

**Comment by felixLam** [comment]
The method you are looking for is `SumupSDK.presentLoginFromViewController(...` code completion should help you with the rest.

**Comment by pradeepkumari** [comment]
How to call that objective c method from my swift?Pls give me code for login action .....

**Comment by pradeepkumari** [comment]
func loginButtonAction(sender: AnyObject)
    {
//Please update code here.Am not able to call SumupSDK.presentLoginFromViewController. having bridging header. Whether i need to import that sumupsdk class in that.
}

**Comment by pradeepkumari** [comment]
https://gist.github.com/pradeepkumari/c08b985b558d909b509a30f9e3ca04f6

**Comment by pradeepkumari** [comment]
Anybody helpout this issue?

**Comment by felixLam** [comment]
Here is the swift code from the forthcoming swift sample app:
```swift
// present login UI and wait for completion block to update button states
SumupSDK.presentLogin(from: self, animated: true) { [weak self] (success, error) in
    guard error == nil else {
        // errors are handled within the SDK, there should be no need
        // for your app to display any error message
        return
    }

    self?.updateButtonState()
}
```

**Comment by felixLam** [comment]
Feel free to open a new issue if you have other issues or re-open this one if the above code does not work as you expected.

**Comment by felixLam** [comment]
Also ensure to add the Bundle Identifier of your iOS app to your API Keys `Application identifiers` in the developer portal.

**Comment by pradeepkumari** [comment]
Am not able to type SumupSDK.presentLogin(from: self, animated: true) { [weak self] (success, error) ...It s not allowing to type method name.

**Comment by felixLam** [comment]
What is the compiler error that you receive?

**Comment by pradeepkumari** [comment]
SumupSDK.checkoutWithRequest(request, fromViewController: self) { [weak self] (result: SMPCheckoutResult?, error: NSError?) -> Void  in

This line shows error like this:
Cannot convert value of type '(SMPCheckoutResult?, NSError?) -> Void' to expected argument type 'SumupCompletionBlock?'

**Comment by pradeepkumari** [comment]
There @felixLam ?

**Comment by pradeepkumari** [comment]
@mollidor @felixLam  help out. I stuck with this issue

**Comment by mollidor** [comment]
@pradeepkumari 
@felixLam kindly provided a sample app written in Swift 3. Please see https://github.com/sumup/sumup-ios-sdk/tree/swift-sample-app

**Comment by pradeepkumari** [comment]
This sdk only am using. But my code is in swift.Thats my main problem. @felixLam  provide me sample swift app.I will be going thru this issue for the past 3 days.

**Comment by felixLam** [comment]
The sample app illustrates how the SDK can be used in swift. Please have a look there. You should not write NSError, but only Error in the completion block parameter declaration. See https://github.com/sumup/sumup-ios-sdk/blob/swift-sample-app/SumupSDKSampleApp-Swift/SumupSDKSampleApp/ViewController.swift

**Comment by pradeepkumari** [comment]
Issue:
1. Type "SumupSDK" has no member "Checkout" 
2. Use of undeclared "error"

**Comment by pradeepkumari** [comment]
@felixLam there?  Use of undeclared "error". Am not able to use Error variable

**Comment by pradeepkumari** [comment]
@mollidor there?

**Comment by felixLam** [comment]
Did you try copying the code from the sample app? Please be aware that swift is case sensitive.

**Comment by pradeepkumari** [comment]
Yes i did...Still getting Error.....But login button in one view and charge button in another view...

**Comment by felixLam** [comment]
Please post a gist with the code that causes compiler issues.

**Comment by pradeepkumari** [comment]
My login button action.It shows sumup login view. but i dont want that. i want charge button view  if i click login button in my app login button.
https://gist.github.com/pradeepkumari/07adde7b30aa9009cbcfae162881acd9

**Comment by pradeepkumari** [comment]
My charge button view:
https://gist.github.com/pradeepkumari/75f9ffa0b1b423eb98130d5e59e9fa69

**Comment by pradeepkumari** [comment]
@felixLam  shall i send my project? Just run its simple. Able to view issue clearly

**Comment by felixLam** [comment]
As noted before "error: NSError?" should be "error: Error?"  Please take another close look at the sample app code and follow the suggestions above.

**Comment by pradeepkumari** [comment]
If i put error it shows issue:
1. Type "SumupSDK" has no member "Checkout" 
2. Use of undeclared "error"

**Comment by pradeepkumari** [comment]
Send ur mail id? I need small help.....Just i want to remove the sumup login screen. Just if i login from my own app screen , it should show charge button screen.

**Comment by felixLam** [comment]
The SumUp SDK requires users to login with their merchant login. Please understand that this is a different login than your app's login. It is not possible to use the Sumup SDK without a Sumup login. We need to know which merchant is using the app in order to process payments.

**Comment by pradeepkumari** [comment]
But in android they are doing. So client want only single signup that too in their own page.

**Comment by pradeepkumari** [comment]
Also transaction is not happening. If i put error also shows error, if i put nserror also shows error.

**Comment by mollidor** [comment]
You can acquire a token from SumUp's API. I think I've seen your code
snippet doing that in this or another issue you opened. You'll find a link
to the respective online documentation in the SDK's header documentation.
Once you have the token you can call loginwithtoken, handle the completion
block accordingly and the use checkout just like the sample app does.

pradeepkumari <notifications@github.com> schrieb am Sa. 12. Nov. 2016 um
12:04:

**Comment by pradeepkumari** [comment]
@mollidor there?

**Comment by pradeepkumari** [comment]
Need your help.Do you team viewer?
