### ISSUE TITLE
Not presenting checkout as user is not logged in.

### ISSUE THREAD

**Issue by raghubb4444** [sumup/sumup-ios-sdk#27]
i want to present card terminal view after i click my login button.This is my code:
https://gist.github.com/pradeepkumari/f5e6f78e8085d70d1a19d1141424d84a

**Comment by felixLam** [comment]
Hello Raghub,
Are you using two accounts to comment on issues? This is confusing and increases our work load. 
Kind regards

Felix

**Comment by raghubb4444** [comment]
One of my colleague also working on that. Now i newly started. This is my code. Just go through

**Comment by raghubb4444** [comment]
We stuck with this issue for the past 4 days.Just a help..

**Comment by mollidor** [comment]
Hi Raghub. 

As we tried to outline in a different issue you or one of your co-workers opened you can either
1) call [presentLogin...](https://github.com/sumup/sumup-ios-sdk/blob/develop/SumupSDK.embeddedframework/SumupSDK.framework/Versions/A/Headers/SumupSDK.h#L80) which will show a login view controller where the merchant has to manually enter his username and password, then tap "Login". This is what the sample app provided does. Build and run and you will see it in action.
2) Advanced: Acquire a token from SumUp's API, which is what you seem to be doing here. You will then have to call [loginWithToken:](https://github.com/sumup/sumup-ios-sdk/blob/develop/SumupSDK.embeddedframework/SumupSDK.framework/Versions/A/Headers/SumupSDK.h#L85-L92) providing this token. Once the completion block has run indicating success you can go ahead and call [checkoutWithRequest](https://github.com/sumup/sumup-ios-sdk/blob/develop/SumupSDK.embeddedframework/SumupSDK.framework/Versions/A/Headers/SumupSDK.h#L117-L126) just like the sample app does.

So either `presentLogin...` OR acquire token and `call loginWithToken:..`

**Comment by felixLam** [comment]
Please clarify these questions for us:

1. do you want to open the SumUp app or do you want to present SumUp screens within your app?
2. did you integrate your backend with the SumUp backend so that you receive an authentication token or do you want your users to manually login in?
3. which version of Swift do you use?
4. which iOS SDK is your base SDK?
5. which iOS Version is the lowest that you plan on supporting?

Please stop opening support issues under multiple user names on multiple repositories. We are trying to help you, receiving a barrage of issues and comments does not speed up the process. To the contrary. 

Kind regards 

Felix

**Comment by raghubb4444** [comment]
@felixLam sorry for my mistake.
1. Want to present sumup screens within my app and also integration.
2. I didn't get you what you are asking? just i added sumup libraries in my project and also opened account in sumup and linked my project to that account.also added api key to my appDelegate.
3. swift 2.2
4. sumup-ios-sdk(currently we are commenting know, that sdk only am integrated)
5. 6

**Comment by raghubb4444** [comment]
2. i am getting accesstoken and merchant code in my response. Just check my gist.

**Comment by mollidor** [comment]
okay, so you are at (2) in my [comment above](https://github.com/sumup/sumup-ios-sdk/issues/27#issuecomment-260595475)
> You will then have to call loginWithToken: providing this token. Once the completion block has run indicating success you can go ahead and call checkoutWithRequest just like the sample app does.

**Comment by raghubb4444** [comment]
After passing Username and password to sumup request am getting response with accesstoken and merchant code. After that, I have to call present login method or login with token.

**Comment by mollidor** [comment]
You have to call `loginWithToken:` with that token, *not* `presentLogin...`. Just read my comment above https://github.com/sumup/sumup-ios-sdk/issues/27#issuecomment-260595475 once again.

**Comment by raghubb4444** [comment]
ok.what should i pass in that completion argument? is it Right?
 SumupSDK.loginWithToken(Appconstant.access_token, completion:{ [weak self] (success, error) in
                        guard error == nil else {
                            return
                        }    
                        })

**Comment by raghubb4444** [comment]
If i click login means, It shows same error.Not presenting checkout as user is not logged in.

**Comment by raghubb4444** [comment]
@felixLam small help. Just am clicking login button first time it shows card terminal view. Then if i click cancel in card terminal view, it comes back and shows login view. But now if i click login(second time) means, it enters into error loop in completion block

**Comment by raghubb4444** [comment]
@felixLam @mollidor  small issue? After the card terminal view, If i connect t device and type the value, it closes the app.what may be the issue?

**Comment by felixLam** [comment]
Have the other issues been resolved then? Please provide a crash log.

**Comment by raghubb4444** [comment]
@felixLam  Other issues are solved. I didn't have Device with me. Client is only having device. Just i sent the .ipa.He is saying that, after the card insertion it closes the app like that.What may be the problem?

**Comment by mollidor** [comment]
@raghubb4444 Please provide a crash log.

**Comment by felixLam** [comment]
Without a crash log it is really hard to say. 
The crash is most likely in your code. Previously you had many lines where you force unwrap an optional variable (using !). This is always bad. Use guard let or if let instead and check that the variable is not nil before accessing any of its properties/methods otherwise you will receive a lot of crashes.

**Comment by felixLam** [comment]
Given that you reported the initial issues as resolved I am closing this issue. For the crash: please follow common swift debugging practices. This is not an issue with the SDK.

**Comment by raghubb4444** [comment]
I didn't have device. I am able to check using the device.Card insertion closes the app like he is saying

**Comment by felixLam** [comment]
I did not deny that you are witnessing crashes, however without a symbolicated crash report it will be impossible to help you.

**Comment by raghubb4444** [comment]
@felixLam There? please go through my code for sumup.
https://gist.github.com/raghubb4444/3e780ce8a1f772b860c2345b79ee4f6b

**Comment by felixLam** [comment]
The only think that strikes me is that you do not use the merchant's currencycode and instead always use USD. We had discussed this earlier and the sample app provides appropriate sample code. Does your IPA have assertions enabled? Again without the crash logs we will not be able to help you in any meaningful way. Please learn how to collect, symbolicate and interpret crash reports.

**Comment by felixLam** [comment]
This is also possible with external installations and is not limited to debugging sessions. Have a look at crashlytics or hockeyapp

**Comment by raghubb4444** [comment]
This is my app. App closes after inserting card.
https://www.youtube.com/watch?v=t14Y_bt7mPU

**Comment by raghubb4444** [comment]
Crashlytics shows error.

**Comment by mollidor** [comment]
Can you please provide the crash log. You can download it from the device using Xcode if you don't want to integrate HockeyApp/Crashlytics.

**Comment by raghubb4444** [comment]
@felixLam  there?Please helpout.

**Comment by mollidor** [comment]
Which version of the SDK are you using? If you are using 1.3 please make sure to follow the steps here: https://github.com/sumup/sumup-ios-sdk#supported-device-orientation

Feel free to move to 1.3.1b which doesn't need you to support landscape anymore: 
https://github.com/sumup/sumup-ios-sdk/tree/develop

https://github.com/sumup/sumup-ios-sdk/blob/develop/CHANGELOG.md#version-131b1

**Comment by raghubb4444** [comment]
App executed by client. just i sent .ipa and he executed the app. That is that video. Am not able to get crash log. I installed crashlytics. But its not showing crash report. Please helpout as a individual.

**Comment by raghubb4444** [comment]
Do you have teamViewer? Please helpout. My client scolding lot.

**Comment by mollidor** [comment]
Did you read and follow my thoughts in https://github.com/sumup/sumup-ios-sdk/issues/27#issuecomment-261263867 ?

You should at least be able to tell us 
a) which version of the SDK you are integrating
b) if the app you built support a landscape orientation https://github.com/sumup/sumup-ios-sdk/blob/master/SumupSDKSampleApp/SumupSDKSampleApp-Info.plist#L54-L60 (if on SDK 1.3)

**Comment by raghubb4444** [comment]
Following 1.3 only.

**Comment by mollidor** [comment]
You will **have** to support one of the two landscape orientations if you are using 1.3
See Readme and sample app:
https://github.com/sumup/sumup-ios-sdk#supported-device-orientation
https://github.com/sumup/sumup-ios-sdk/blob/master/SumupSDKSampleApp/SumupSDKSampleApp-Info.plist#L54-L60

If you can not support a landscape orientation I would suggest to integrate the latest 1.3.1 Beta version to be found here:
https://github.com/sumup/sumup-ios-sdk/tree/develop

It should be a drop in replacement.

**Comment by raghubb4444** [comment]
It is in my info.plist
</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>

**Comment by mollidor** [comment]
Yes, that's iPad. The video you shared is an iPhone.

**Comment by raghubb4444** [comment]
I have to run it in iphone. I selected only potrait orientation. Don't need landscape.
But i used 1.3. What can i do now?

**Comment by mollidor** [comment]
I outlined your options 10 minutes ago: https://github.com/sumup/sumup-ios-sdk/issues/27#issuecomment-261274481

**Comment by raghubb4444** [comment]
Ok. but i already did 1.3. What is the difference?Or i have to add this 1.3.b framework from the first

**Comment by mollidor** [comment]
Just drop in 1.3.1b2 from the develop branch of this repo. There's a changelog which I've linked to before: https://github.com/sumup/sumup-ios-sdk/blob/develop/CHANGELOG.md

**Comment by raghubb4444** [comment]
in xcode, what i have to change?

**Comment by raghubb4444** [comment]
Still getting error. If i insert a card, app closes.

**Comment by raghubb4444** [comment]
https://gist.github.com/raghubb4444/3e780ce8a1f772b860c2345b79ee4f6b

**Comment by mollidor** [comment]
Did you make changes to your app? Did you move to SDK 1.3.1b2 ?
