### ISSUE TITLE
Refund transaction

### ISSUE THREAD

**Issue by iabdullin** [sumup/sumup-ios-sdk#28]
Hello team,

      Haven't found refund transaction in your SDK. Is it supported? If not, how merchant is supposed to refund charged funds from POS?

Thanks,
Ildar

**Comment by konradfeketesumup** [comment]
Dear Ildar,

Refunds can be initiated by using the respective API documented under the link below:
https://sumup.de/docs/rest-api/transactions-api/#merchant-refunds

Best regards

**Comment by thom-ek** [comment]
Why not to implement all API methods in SDK?
