### ISSUE TITLE
Backend modifications ?

### ISSUE THREAD

**Issue by plutch14** [sumup/sumup-ios-sdk#29]
Hi,

We have an application that hasn't changed since december 2016 and since a few days, we can't use the SDK like before.

The login screen is displayed but right after, we are getting this message in the log :
 - SumupSDK: Not presenting checkout as user is not logged in.

If I try again right after, I'm getting :
 - SumupSDK: Not presenting checkout as checkout is already in progress
 - SumupSDK: error: SDK has been setup before.

We are using the version 1.2.2 which was super stable since now and I'm using iOS 10.2.

Regards,

David

**Comment by mollidor** [comment]
Hi @plutch14 

So the completion block of `presentLoginFromViewController:...` gets run and indicates success, but a subsequent `checkoutWithRequest:fromViewController:completion` prints the log you mentioned? 

Would you mind upgrading to 2.0? 

Regards,
Lukas

**Comment by plutch14** [comment]
The issue has been solved by email, thank you Lukas !
