### ISSUE TITLE
Missing API?

### ISSUE THREAD

**Issue by thom-ek** [sumup/sumup-ios-sdk#3]
On https://sumup.co.uk/integration I read about App Switch and `SMPPaymentRequest` class. Where I can find it?

**Comment by mollidor** [comment]
Hi Tomasz.

It's missing indeed, will check. Sorry for the inconvenience.

Regards,
Lukas

**Comment by mollidor** [comment]
Hi Tomasz.

You should find everything you need here: https://github.com/sumup/sumup-ios-url-scheme
Sorry for not providing this earlier.

Regards,
Lukas
