### ISSUE TITLE
Bypass SumUp Login Screen by Passing Credentials through code

### ISSUE THREAD

**Issue by floralfrog-developers** [sumup/sumup-ios-sdk#30]
Dear Support Team,

We are developing an ePOS app that runs as a WebView App in IOS and Android. We are now integrating SumUp Card Reader with this. The idea is to call javascript functions from the enclosed webpage in our app to call IOS and Android functions to make the payment. 

But the Sample app that we downloaded as part of your SDK, shows a Login Screen for SumUp when the app opens and user has to login through this before making any transactions. Is it possible to pass the SumUp login Credentials through code in some way, so that the screens and flow match better to our App. Or any means we can customise that ?

Our IOS Container App is being developed in Swift 3 and XCode 8.2.1

As the development time is short, your help & suggestions will make the integration smoother...

Thanks & Regards
Developer

**Comment by MarvinOS** [comment]
You could use the following method I guess:

```
/**
 * Logs in a merchant with an access token acquired via https://sumup.com/integration#APIAuth
 * Make sure that no user is logged in already when calling this method.
 *
 *  @param aToken an access token
 *  @param block  a completion block that will run after login has succeeded/failed
 */
+ (void)loginWithToken:(NSString *)aToken completion:(nullable SumupCompletionBlock)block;
```

**Comment by floralfrog-developers** [comment]
Thanks MarvinOS,
Let me try...
Regards

**Comment by mollidor** [comment]
@MarvinOS thanks for helping out.

@floralfrog-developers 
This would be the way indeed. Feel free to get in touch via integration@sumup.com if you need help.

**Comment by floralfrog-developers** [comment]
OK, I am going though the docs again to implement MarvinOS's suggestion. 
I may ask further queries during integration...

Thanks Mollidor

**Comment by floralfrog-developers** [comment]
Hi @mollidor , @MarvinOS ,

I was going through the docs for obtaining Token through OAuth Process https://sumup.com/docs/oauth/.
But apart of development, the process mentioned seems to be difficult for our clients, those will install our App and the SumUp Card Reader to make it work. 

So it seems like we have to use the login screens and call them somewhere inside our application.

On another note:
By following the Sample application we are embedding the SumUp SDK framework and initializing with SumupSDK.setup(withAPIKey: ".......")

But the Key is generated from our SumUp Account Developer Dashboard. Will the same key work for all our clients those will install the app and use their SumUp Card Reader?

Thanks & Regards
floralfrog-developers

**Comment by mollidor** [comment]
Hi @floralfrog-developers 

Yes, you will need just one API key per application. The key is associated with your account and you will have to whitelist your bundle identifier. There's no need to create multiple API keys as you can whitelist multiple bundle identifiers to also support a development version of your application.

Your clients will authenticate with their own SumUp credentials just like they would when using the SumUp app.

Regards,
Lukas

**Comment by floralfrog-developers** [comment]
OK, Good. 

Thank You Lukas

**Comment by floralfrog-developers** [comment]
Hi @mollidor , @MarvinOS ,

i posted my query to as email to integration@sumup.com, will that be ok, or postig issues through this github channel would be faster?

Regards

**Comment by mollidor** [comment]
Either way should do, an email is probably the better way if you have some specific questions. 

Regards,
Lukas
