### ISSUE TITLE
Customize checkout screen

### ISSUE THREAD

**Issue by Alkashi** [sumup/sumup-ios-sdk#31]
Is it possible to change the bg color and more on the screen that appears for a checkout ? i.e. after calling [SumupSDK checkoutWithRequest:request fromViewController:self ...] ?

Many thanks.

**Comment by mollidor** [comment]
Hi.

That's not supported currently. What exactly would you like to tweak?

Regards,
Lukas

**Comment by Alkashi** [comment]
Change the bd color, add the logo of my client etc....

**Comment by mollidor** [comment]
Hi @Alkashi .

Feel free to send an email to integration@sumup.com outlining the features you are missing.

Regards,
Lukas
