### ISSUE TITLE
Skip "transaction successful" screen

### ISSUE THREAD

**Issue by Alkashi** [sumup/sumup-ios-sdk#32]
Hi,

Is it possible to skip or at least to know when the the "transaction successful" window has been presented ?
Now, after the user has entered his pin code and everything gone right, the completion block with result.succes is called only when the user tapper the "Skip" button on the "transaction successful screen".

I want to know exactly when the user has correctly entered his pin code.

Is there a way to do it ?

**Comment by mollidor** [comment]
Hi Alkashi.

This is currently not possible. We are working on a feature where you would be able to make the SDK not present the "ask for receipt" screen.

Getting a callback when the user has entered his PIN is not supported at the moment. Not all transactions require PIN entry as it depends on the interface used (chip/contactless/swipe), the transaction amount and the card provided. So even a successful transaction might not give you a PIN entry event at all.

Feel free to follow up on integration@sumup.com to tell us more about your use case and feature requests.

Regards,
Lukas
