### ISSUE TITLE
Crash reports SDK

### ISSUE THREAD

**Issue by asa47** [sumup/sumup-ios-sdk#33]
Hello guys,
We received some crash reports, could you please help us investigating the cause of the issue?
We had four occurrences in the last week, and I am trying to understand if it is caused by us or it is from the SDK.

The following is the crash summary:
LOCATION:			[SMPBluetoothManager connectToReader:hasBeenRetrieved:updateBlock:]
EXCEPTION:			NSInternalInconsistencyException
MESSAGE:			Invalid parameter not satisfying: peripheral != nil
LAST INTERACTION:	Display SMPPaymentCardReaderVC

Thanks!

**Comment by mollidor** [comment]
Hi.

Thanks a lot for the report. We'll look into it asap. We'll let you know as soon as we have a fix.

Which SDK version are you currently on?
Can you give us a hint to what state the reader was in before your last interaction?
Was it already awake or did you expect the SDK to wake it up?
Did you do a transaction before or did it happen on the first tx after app launch?

Thanks a lot for your help and sorry for the inconvenience caused.

Regards,
Lukas

**Comment by asa47** [comment]
Hello Lukas,

Thanks for the quick reply, and we are currently on the 2.1 version of the SDK.
Unfortunately, we do not know in which status was the reader, we received those crashes from our customers. We tried to replicate the crashes in our development office but we had no luck.

Let me know, if you find something. 
Thanks a lot!

**Comment by mollidor** [comment]
Hi @asa47 

Would you mind giving v2.2 a try? We believe this issue is fixed. Feel free to re-open if needed. 

Kind regards,
Lukas

**Comment by fetzig** [comment]
@mollidor has not been fixed. got a crash report in yesterday.

iPad mini with iOS 9.3.5
memory on device was low (8mb free). maybe that helps.

seems like i can't reopen myself. please do this for me.
