### ISSUE TITLE
adding SDK

### ISSUE THREAD

**Issue by raphaels17** [sumup/sumup-ios-sdk#35]
Hi 

I usually use cocoapod and adding the SDK is more challeging than I tought I keep getting "no module SumupSDK"
I have copied the SumupSDK.embeddedframework to my project, as well as created a bridge file and ensure the framework was in linked Framework but to no avail. Am i missing something?

**Comment by mollidor** [comment]
You might want to take a look at the sample project provided with the SDK.
It includes a swift  bridging header.

**Comment by mollidor** [comment]
Closing this one as I assume you succeeded https://github.com/sumup/sumup-ios-sdk/issues/19#issuecomment-283930027 .
