### ISSUE TITLE
Firemonkey issue

### ISSUE THREAD

**Issue by mscrocdile** [sumup/sumup-ios-sdk#36]
Hello, 
I try to use static SumupSDK in Firemonkey(Delphi) project.
Do you have any idea what does this error mean?

[DCC Error] E2597 ld: 64-bit LDR/STR not 8-byte aligned: from -[ISHCarouselWithButtonsViewController initWithNibName:bundle:] (0x1008820D0) to l011@0x000007A8 (0x100AE4354) for architecture arm64

**Comment by mollidor** [comment]
Unfortunately we have absolutely no experience with Firemonkey/Delphi. You probably might want to look at this similar issue: https://github.com/openframeworks/openFrameworks/issues/3984.
