### ISSUE TITLE
Regarding Login issue

### ISSUE THREAD

**Issue by pradeepkumari** [sumup/sumup-ios-sdk#38]
Hi am getting Error Code=20(SumupErrorAccountGeneral).What is the issue?

**Comment by mollidor** [comment]
Hi.

Hard to tell. Is that on login or checkout? Is your account activated correctly? You can try to log into that account using the SumUp app or at https://me.sumup.com/login  and see if there's additional information needed.

Regards,
Lukas

**Comment by pradeepkumari** [comment]
It is used to login before. Now only i am unable to login. The login SDK returns 

Error Domain=SumupSDKError Code=20 "(null)" UserInfo={NSUnderlyingError=0x7f98a897fcf0 {Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://triangle.sumup.com/api/0.1/auth, NSErrorFailingURLStringKey=https://triangle.sumup.com/api/0.1/auth}}}

**Comment by mollidor** [comment]
Can you log in to https://me.sumup.com/login and see if that works?

**Comment by pradeepkumari** [comment]
Ya i am able to do login.

**Comment by mollidor** [comment]
Are you still on SDK 1.x? You will have to update to 2.x as the certificates included in 1.x did expire on Feb 24th. See https://github.com/sumup/sumup-ios-sdk/releases.

**Comment by pradeepkumari** [comment]
How to update from 1.x to 2.x?

**Comment by mollidor** [comment]
Should be a simple replacement of your 1.x SDK.

What to do exactly depends on your integration:
If you added this repo as a submodule just checkout tag `v2.1` in that submodule. If you downloaded a zip and copied the files in place, repeat with https://github.com/sumup/sumup-ios-sdk/archive/v2.1.zip from https://github.com/sumup/sumup-ios-sdk/releases/tag/v2.1

**Comment by pradeepkumari** [comment]
Whether i have to add all the files from sdk 2.1 or replacing SumupSDK.framwork alone is enough to update?

**Comment by mollidor** [comment]
Remove all files from 1.x and drop in 2.1 including `Resources`. Basically delete your `SumupSDK.embeddedframework` directory and put the one from v2.1 in place.

**Comment by raphaels17** [comment]
Hi 

I face the same issue. however I doubt this  is due to a version issue cause I have download the SDK in March. How can I check which version I am running on ?

regards

raphael

**Comment by mollidor** [comment]
Hi @raphaels17 

I you downloaded in March you should be good. You can call `+[SumupSDK bundleVersionShortString]`.

**Comment by pradeepkumari** [comment]
ya It works fine now. Thank you

**Comment by mollidor** [comment]
Closing this.
@raphaels17 feel free to get in touch at integration@sumup.com if your problems persist.
