### ISSUE TITLE
Cancel payment process while checkout

### ISSUE THREAD

**Issue by tbaranes** [sumup/sumup-ios-sdk#39]
The user has no possibility to cancel the checkout from the iOS interface, he has either to wait until the process timeout or clicked on the cross of the sumup box which generate a transaction FAILED.

Isn't possible to add a simple cancel button in the checkout interface?

**Comment by mollidor** [comment]
Hi.

Adding a cancel button in the interface is simple, indeed. Cancelling the transaction correctly is more tricky unfortunately. 

It's on our roadmap but I can't give you an estimate. You can cancel the transaction from the terminal. On Air readers you can press the power button to do so.

Regards,
Lukas

**Comment by Alkashi** [comment]
Hi @mollidor 

Any update about the ability to cancel a checkout ?
Many thanks.

**Comment by mollidor** [comment]
Hi @Alkashi . 

As it stands pressing the power button on the card terminal is the way to go. We are working on improvements in the merchant facing UI to highlight that option.

Regards,
Lukas

**Comment by shagedorn** [comment]
Duplicate issue of #6 .

**Comment by jblevins1991** [comment]
After 3 years do you guys have a solution to this? It looks really unprofessional and can lose the business owner money from sales to reboot the device every single time this happens.

**Comment by jahenry** [comment]
@jblevins1991  Thanks for raising here.  I understand your perspective and fully agree that it's an important addition to the SumUp solution!  

Nonetheless, due to the nature of our existing card reader setup and security requirements, it's not a 'quick fix'.  Currently to cancel a transaction, a user may make a short 'tap' the power button on the right side of the unit to abort the transaction mid flow.  Please note, if the payment card has been inserted, a user may also select the red 'X' to cancel a transaction.

Appreciate the frustration and we do have the addition in our backlog to deliver.  In the meantime, the team has been working hard to deliver many of the requested additions from our current customers and partners!  Please do follow our repos and we'll keep you posted on all the latest product improvements :-)

James

**Comment by cuddeford** [comment]
Our implementation is contactless only and the terminals are hidden from customers, so the ability to cancel a transaction by pressing the physical button is not an option.

It would be great to have a cancel button in the SDK as at present they have to wait ages for it to timeout.

**Comment by JullianSU** [comment]
Hi Cuddford, 

Thank you for your message, would you be able to share a bit more of your use case at integration@sumup.com? 

Many thanks,

**Comment by al-iskandar-github** [comment]
> @jblevins1991 Thanks for raising here. I understand your perspective and fully agree that it's an important addition to the SumUp solution!
> 
> Nonetheless, due to the nature of our existing card reader setup and security requirements, it's not a 'quick fix'. Currently to cancel a transaction, a user may make a short 'tap' the power button on the right side of the unit to abort the transaction mid flow. Please note, if the payment card has been inserted, a user may also select the red 'X' to cancel a transaction.
> 
> Appreciate the frustration and we do have the addition in our backlog to deliver. In the meantime, the team has been working hard to deliver many of the requested additions from our current customers and partners! Please do follow our repos and we'll keep you posted on all the latest product improvements :-)
> 
> James

It's now 2021. People have been complaining about the absence of this feature for almost the entirety of the product's lifespan, and for it to still not be resolved is inexcusable. It may not be something you can bash out in a few hours, but it's certainly something that could be solved in literal years. 

Moreover, while it's possible to cancel a transaction if there's a card inserted into the SumUp reader, this doesn't help at all when it comes to contactless. Hell, unless you're very precise then even moving the card near the device to try and insert will trigger it, causing a bad transaction to go through that will then need to be reversed. 

Despite contactless being ubiquitous, it's like none of your team have actually taken into account that it's been widespread and increasingly dominant for years at this point. Why are you so behind the curve here?

Hell, if it's so incredibly complex and difficult to do, why do many of your competitors offer this on their machines? The only real conclusion that you're leaving here is that the SumUp coding team is either poorly led, or else that they are outright incompetent when compared to other competitors. Neither option reflects well on you.
