### ISSUE TITLE
Fix Info.plist files for iOS 9.0

### ISSUE THREAD

**Issue by dclerc** [sumup/sumup-ios-sdk#4]
In order to be able to submit our app with XCode 7 we need the Info.plist files of the two resource packages found in the SumUp SDK to be fixed according to the new plist rules for bundle resources (remove the "Executable File" entry).

Thanks!

**Comment by mollidor** [comment]
Hi dclerc.

Thanks for raising this. I wasn't aware. Can you give me the exact error you get and/or a link to what needs to be removed? I will try to build a new version as soon as possible then.

Regards,
Lukas

**Comment by dclerc** [comment]
Search for "ITMS-90535" in Google. The first StackOverflow hit has a screenshot of the error message and the fix (remove CFBundleExecutable key from Info.plist in the two resources bundles that are included in the SumUp SDK).

I removed these keys manually and was able to proceed with the App Store upload.

**Comment by mollidor** [comment]
Thanks a lot. Will fix this in the next Beta. Happy to hear you were able to work around this. Sorry for the inconvenience.

**Comment by mollidor** [comment]
Fixed in 1.2.1.
