### ISSUE TITLE
"Server error", how to debug it?

### ISSUE THREAD

**Issue by tbaranes** [sumup/sumup-ios-sdk#40]
We are getting that error `Server Error - Something went wrong! Please try again`, but we don't have any information from the checkout response. The only information we have is that `success` is false.

In which cases are we supposed to get that error? How are we supposed to handle it?

**Comment by mollidor** [comment]
Hi.

You can start by evaluating the error and it's underlying errors or the additional info of the result object. If you can't find any hint, feel free to follow up at integration@sumup.com and we try to dig into it.

Regards,
Lukas
