### ISSUE TITLE
Checkout preferences not launching

### ISSUE THREAD

**Issue by MarvinOS** [sumup/sumup-ios-sdk#44]
````
dispatch_async(dispatch_get_main_queue(), ^{
        [SumupSDK presentCheckoutPreferencesFromViewController: controller
                                                      animated:NO
                                                    completion:^(BOOL success, NSError *error) {
            NSLog(@"Error", [error localizedDescription]);
        }];
    });
````

Does not work and neither shows a modal. However, the presentLoginFromViewController with the same arguments does work as expected..

**Comment by felixLam** [comment]
Hello @MarvinOS,

just to be sure: is the user logged in when you call `presentCheckoutPreferencesFromViewController`?  Is anything printed to the console log?

Kind regards,

Felix

**Comment by MarvinOS** [comment]
Hi Felix,

Yes, user is logged in, and nothing is printed to the console. However, when calling the same window again the completion block is executed.

**Comment by felixLam** [comment]
Have you checked that the controller is not nil when the block is executed on the main thread?
