### ISSUE TITLE
checkout is crashing

### ISSUE THREAD

**Issue by princefr** [sumup/sumup-ios-sdk#45]
hi guys, when i try to initiate a checkout my app crash with this error.
[SMPPaymentCardReaderVC topLayoutInset_ISH]: unrecognized selector sent to instance.

this is what my integration code look like where `[UIApplication sharedApplication].keyWindow.rootViewController` represent the view controller, i'm calling it from c++, the login and open preferences works well but not the checkout
```
      SMPCheckoutRequest *request = [SMPCheckoutRequest requestWithTotal:[NSDecimalNumber decimalNumberWithString:productAmount]
                                                                   title:productTitle
                                                            currencyCode:[[SumupSDK currentMerchant] currencyCode]
                                                          paymentOptions:SMPPaymentOptionAny];

              [request setForeignTransactionID:foreignRef];

              [SumupSDK checkoutWithRequest: request
                          fromViewController: [UIApplication sharedApplication].keyWindow.rootViewController
                                    completion: ^(SMPCheckoutResult *result, NSError *error) {
                                              if(error)
                                          @{Pay:Of(_this).Reject(string):Call(@"Vous devez etre connecter")};
                                                else
                                          @{Pay:Of(_this).Resolve(string):Call(@"Le paiement a été effectué")};
                                        
                }];
```

**Comment by felixLam** [comment]
It appears that you missed to follow one of the steps in the setup:

https://github.com/sumup/sumup-ios-sdk#preparing-your-xcode-project

> 4. Add -ObjC to “Other Linker Flags” if not yet included.

Can you verify that the crash is resolved by adding the appropriate linker flag?

**Comment by felixLam** [comment]
Feel free to re-open this issue should the problem persist.
