### ISSUE TITLE
setupWithAPIKey should be called on main thread?

### ISSUE THREAD

**Issue by Zyphrax** [sumup/sumup-ios-sdk#46]
In our app we had some weird issues with SumUp not properly initializing. Most of the UI would work, but the login screen would always return an error.

We found out that the cause was that `setupWithAPIKey` was called on a background thread instead of the main thread. It would be very useful to add this to the README.

For UI methods it makes sense to be called on main.
For `setupWithAPIKey` this is not so apparent.

**Comment by mollidor** [comment]
Thanks for bringing this up. Indeed, there's some `UIAppearance` stuff happening in `setupWithApiKey:`. That's the culprit most likely.

**Comment by Zyphrax** [comment]
> We found out that the cause was that setupWithAPIKey was called on a background thread instead of the main thread. It would be very useful to add this to the README.

Might save other people from wasting a few hours like I did.

**Comment by shagedorn** [comment]
Sorry, I should have closed this with a comment: We have changed this, there will be a note in the README once we release the next version. Thank you for opening the issue.

**Comment by Zyphrax** [comment]
I see it in the changelog, but I don't see it in the latest README:
https://github.com/sumup/sumup-ios-sdk/blob/v3.0b2/README.md

Perhaps change:
> Note: setupWithAPIKey: checks for the user's location permission. Consequently, do not call this method as part of the app launch.

To:

> Note: setupWithAPIKey: checks for the user's location permission. Consequently, do not call this method as part of the app launch. This method should not be called from a background thread, use the main thread instead.

**Comment by shagedorn** [comment]
My comment above was inaccurate: We did not at any point add this note to the README, but to the respective [header documentation](https://github.com/sumup/sumup-ios-sdk/blob/v3.0/SumUpSDK.embeddedframework/SumUpSDK.framework/Versions/A/Headers/SMPSumUpSDK.h#L72) instead. It is now also mentioned in the README.
