### ISSUE TITLE
Error Code: 20 while Login

### ISSUE THREAD

**Issue by raghubb4444** [sumup/sumup-ios-sdk#47]
While Doing Login, Am getting this. But i have updated the Sumupsdk Framework...I am using swift2.0 xcode 7.3.1.

Error Domain=SumupSDKError Code=20 "(null)" UserInfo={NSUnderlyingError=0x79606f70 {Error Domain=JSONRPCServerError Code=-32006 "Version not supported" UserInfo={JSONObject={
    code = "-32006";
    data =     {
        message = "Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-3GBMG)";
    };
    message = "Version not supported";
}, NSLocalizedDescription=Version not supported}}})

**Comment by raghubb4444** [comment]
Please do reply sumup team.

**Comment by mollidor** [comment]
Hi. 

Can you make sure to follow the project setup steps in the readme.

Please see https://github.com/sumup/sumup-ios-sdk#preparing-your-xcode-project (Step 5 specifically) and call +[SumupSDK testSDKIntegration]. It should highlight things you might have missed.

Regards,
Lukas


https://github.com/sumup/sumup-ios-sdk/issues/22

**Comment by raghubb4444** [comment]
These steps only i followed, i am using xcode 7.3.1.I checked with all framework versions. But getting same error code: 20
