### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by jdejuanactionsdata** [sumup/sumup-ios-sdk#48]
I try to request a new SDK Key associated with my active account set in EURO currency but the system returns me Network Error.
I need a new SDK Key since the one you gave me corresponds to another account that defaults to GBP
![network error](https://user-images.githubusercontent.com/31509748/30020323-bb7bb706-9163-11e7-8cc1-1e125ad6227b.png)

**Comment by mollidor** [comment]
Hi. 

Your SDK key does not restrict the currency a merchant can do checkouts with. It's the logged in merchant that governs the currency. So you can use an SDK key associated with your GBP merchant and then login to the SDK via your app with a DE merchant trading in EUR. 

Feel free to drop an email to integrations@sumup.com and we will help you to get set up.

Regards,
Lukas

**Comment by mollidor** [comment]
Closing this now. Feel free to get in touch if you need help.
