### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by 0xced** [sumup/sumup-ios-sdk#49]
The documentation of [SMPCheckoutResult.additionalInfo](https://github.com/sumup/sumup-ios-sdk/blob/69ec65419d40122017510f8f8278b715b2ebf719/SumupSDK.embeddedframework/SumupSDK.framework/Versions/A/Headers/SMPCheckoutResult.h#L27) points to https://sumup.com/integration#TransactionHistoryModel which does not exist anymore.

**Comment by mollidor** [comment]
Thanks for letting us know. Will fix.

**Comment by mollidor** [comment]
You should find the relevant information at http://docs.sumup.com/rest-api/transactions-api/ in the meantime.

Thanks again for highlighting the outdated link.

**Comment by mollidor** [comment]
Should be fixed in latest release. Thanks again for making us aware.
See https://github.com/sumup/sumup-ios-sdk/releases/tag/v2.3.2
