### ISSUE TITLE
The operation couldn’t be completed. (SumupSDKError error 50.)

### ISSUE THREAD

**Issue by MarvinOS** [sumup/sumup-ios-sdk#5]
Hi,

Currently, we've created an test app for testing the SDK. However, after laucnhing the app for the first time, granting the location permission and logging in we receive the following error:

```
The operation couldn’t be completed. (SumupSDKError error 50.)
```

The login responds with success = 1, the checkoutInProgress = 1. The completion block is immediately executed. Result = 0. 

What are reasons for error no. 50? There isn't any documentation for it except 'SMPSumupSDKErrorCheckoutGeneral'.

**Comment by schneider-iosphere** [comment]
Hi,

is there an underlying error (`NSUnderlyingErrorKey`) in the passed errors `userInfo` dict? Do you pass an `UIViewContoller *` to `+checkoutWithRequest:fromViewController:completion:` (Assuming you get the error on using this API)? 

We will try to improve the documentation on `SMPSumupSDKErrorCheckoutGeneral` in the next release.

Best,
Felix

**Comment by MarvinOS** [comment]
````
Underlying Error: Error Domain=JSONRPCServerError Code=6 "Missing Location Parameters." UserInfo=0x155a7c00 {JSONObject={
    code = 6;
    data =     {
        "action_name" = checkoutFlow;
        "endpoint_name" = general;
        message = "Helaas konden we uw locatie niet goed vaststellen. Probeer de app af te sluiten en opnieuw in te loggen, of contacteer ons support team (quote: MML773)";
        trace = "<null>";
    };
    message = "Missing Location Parameters.";
}, NSLocalizedDescription=Missing Location Parameters.}
```

Is there anything possible to check if the location is found?

**Comment by MarvinOS** [comment]
We first have to relaunch the app after granting location permission before the checkoutWithRequest is possible again.

**Comment by MarvinOS** [comment]
Is there any new information about this issue?

**Comment by mollidor** [comment]
Hi Marvin. 

Sorry for not coming back earlier. Does this problem persist or is it only happening on the very first app launch? Is it still an issue when you have granted location permission before?

You can probably try to work around this by creating your own instance of `CLLocationManager` and calling `startUpdatingLocation` on it. Let me know if this helps, we are still trying to figure out why the SDK would not be able to acquire a fix itself. 
What kind of device is this?

Regards,
Lukas

**Comment by MarvinOS** [comment]
Manually creating a CLLocationManager and calling the startUpdatingLocation fixed the problem. 

The problem only exists doing the following steps:
1. Deleting the the app
2. Installing the app again (so it has to request the location permission again)
3. Opening the app
4. Granting permission for location
5. Setting the API key
6. Logging in 
7. Starting a payment

After granting permission there is no issue anymore and the process is working like it should be. 
The device is a iPad 2.

**Comment by mollidor** [comment]
Thanks for the detailed report. That helps a lot.

Regards,
Lukas

**Comment by alvaromb** [comment]
Just FYI, we're experiencing the same issue in our app.

**Comment by mhagmajer** [comment]
+1

Same here:

```
2016-08-09 15:51:00.055 pos[1307:292726] checkoutComplete (null), Error Domain=SumupSDKError Code=50 "The operation couldn’t be completed. (SumupSDKError error 50.)" UserInfo=0x1785a200 {NSUnderlyingError=0x1788fe70 "Missing Location Parameters."}
```

**Comment by mollidor** [comment]
Hi @mhagmajer 

Would you mind giving the current 1.3.0 beta a try? It's available on the [develop branch](https://github.com/sumup/sumup-ios-sdk/tree/develop).

Regards,
Lukas

**Comment by mhagmajer** [comment]
Thanks @mollidor, I'm now using the devel branch.

I tested the example app and it worked perfectly so I did a more thorough investigation. It seems that the location features of the SDK **are only impacted if the SDK is setup right before the payment**. If the setup is done inside the delegate's`didFinishLaunchingWithOptions` all works fine.

**Comment by mollidor** [comment]
Hi @mhagmajer 

thanks for the update. We will amend the documentation to suggest setting up the SDK early on.

Regards,
Lukas

**Comment by raghubb4444** [comment]
I am getting error code : 20 , while doing login...But it was working before days... Already i updated....

**Comment by raghubb4444** [comment]
Please do reply @mollidor

**Comment by mollidor** [comment]
Hi @raghubb4444 

Feel free to open a ticket or get in touch with integration@sumup.com.

I will close this ticket as it was opened for a completely different topic. 

Regards,
Lukas

**Comment by raghubb4444** [comment]
I sent message to   integration@sumup.com. But there is no reply for the past 2 days.
