### ISSUE TITLE
IOS 11 issue

### ISSUE THREAD

**Issue by asa47** [sumup/sumup-ios-sdk#51]
Hello guys,

We are currently not able to process transaction in IOS 11; it throws an exception whenever we call the SumupSDK checkoutWithRequest method:

`[SumupSDK checkoutWithRequest:request fromViewController:self.viewController completion:^(SMPCheckoutResult *result, NSError *error){ ... }`

The following is the exception: 
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 24]'

It wasn't possible to fully symbolicate the crash details; here is a summary:
EXCEPTION:	CALayerInvalidGeometry
MESSAGE:	CALayer position contains NaN: [nan 24]
LAST INTERACTION:	Display SMPPaymentOptionsVC

Could you please help us investigating the issue?

Thanks!

**Comment by mollidor** [comment]
Hi @asa47 

Would you mind giving 2.3.2 (currently only on develop) a try? https://github.com/sumup/sumup-ios-sdk/tree/develop

We hope this very issue is fixed in 2.3.2. If you can confirm it is we would go ahead and publish it officially.

Thanks,
Lukas

**Comment by asa47** [comment]
Hi @mollidor, 
Thanks for the quick reply, and yes I can confirm that the 2.3.2 fixed the issue.
Thank you!

**Comment by mollidor** [comment]
Perfect. Thanks a lot for bringing it up and confirming the fix in no time.
