### ISSUE TITLE
ios 11.0.3 bug

### ISSUE THREAD

**Issue by mzhs-git** [sumup/sumup-ios-sdk#54]
login page cancel key click no response on ipod(ios version:11.0.3)
version 2.3.2

**Comment by mollidor** [comment]
Hi.

Can you elaborate? Does the completion block get executed? If so, what's the parameters it gets called with? Are you able to reproduce this in the sample app(s)?

Regards,
Lukas

**Comment by mzhs-git** [comment]
[SumupSDK presentLoginFromViewController:vc
                                    animated:YES
                             completionBlock:^(BOOL success, NSError *error) {
                                 if (error) {
                                     // errors are handled within the SDK, there should be no need
                                     // for your app to display any error message
                                 }
}];
Working on ios9.3.5, iOS10.0.3 is not working.
completionBlock is not execute

**Comment by mzhs-git** [comment]
I can't reproduce this problem in sample app,sumup sdk is very simple to use,I can't find why it can't work

**Comment by mzhs-git** [comment]
Login button can't logged in, no call doneBlock, just show the login animation

**Comment by mollidor** [comment]
If you can't reproduce in the sample apps it's getting tricky. Some things to check:

1) Did you setup the SDK properly? See https://github.com/sumup/sumup-ios-sdk/blob/master/SumupSDKSampleApp/SrcObjC/SUSAppDelegate.m#L36
2) Is there any log in your console?
3) Make sure that your view controller `vc` doesn't get lost while presenting the SDK
4) What's the view hierarchy? How is `vc` presented?
5) Try putting something like `NSLog(@"completion success: %@, error: %@", @(success), error);` in the completion block just to make sure.

**Comment by mzhs-git** [comment]
Thank you! I find the problem.If there is a navigation controller included A,B,C controller，B call presentLoginFromViewController but the top Viewcontroller is C,the problem is reproduce.
This problem is not in the ipad.

**Comment by mollidor** [comment]
Great. So just make sure to present from the topmost (visible) view controller and don't push/pop while presenting the login.
