### ISSUE TITLE
version not supported error while trying to log in with token

### ISSUE THREAD

**Issue by princefr** [sumup/sumup-ios-sdk#56]
hi guys I've this issue when I try to log  into sumup using a token 

```
Error Domain=com.sumup.sdk Code=20 "(null)" UserInfo={NSUnderlyingError=0x600000e4b940 {Error Domain=JSONRPCServerError Code=-32006 "Version not supported" UserInfo={NSLocalizedDescription=Version not supported, JSONObject={
    code = "-32006";
    data =     {
        message = "Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-ZNI3Q)";
    };
    message = "Version not supported";
}}}}
```
regards

**Comment by broomburgo** [comment]
@princefr Hi, how did you solve this? Thanks

**Comment by ChrisMyrants** [comment]
We had the same problem. In our case, `SMPSharedResources.bundle` was missing in our project.
After that we imported it and added to our target, error disappeared.

**Comment by princefr** [comment]
as @ChrisMyrants pointed it out, the error is due to the missing ressource file in your project `SMPSharedResources.bundle`.

**Comment by mollidor** [comment]
Hi all.

Happy to see you were able to fix the issue. The [testIntegration method](https://github.com/sumup/sumup-ios-sdk/blob/master/SampleApp/SumUpSDKSampleApp/SrcSwift/AppDelegate.swift#L19-L23) might help you to double check your integration.

Regards,
Lukas
