### ISSUE TITLE
Add Refunds feature to the SDK

### ISSUE THREAD

**Issue by Ceroce** [sumup/sumup-ios-sdk#58]
As confirmed by the support team, the SDK can not handle Refunds yet.
Please add this feature to the SDK, since refunds can only be issued using the REST API right now, which is a lot of work: we must implement OAuth authentification and provide a GUI for this purpose.

**Comment by ServicePal** [comment]
+1. Alternatively, I suggest SumUp share the code used to build their own iOS app with partners, so we can use that as a starting point. But, making most of the REST API available through the SDK would be preferred.

**Comment by Ceroce** [comment]
I might be wrong, but AFAIK SumUp's own app does not allow refunding either.

**Comment by jahenry** [comment]
Hi all
Appreciate your feedback - 
SumUp's free App does indeed support Refunds, however you are correct that SumUp's SDKs do not currently have refunds embedded.  We offer the REST API to developers for refunds as to enable the greatest use case coverage and flexibility across platform/channel, nonetheless, we're always looking to improve our developer offerings.  Please follow the repo and we'll get you updated on all the latest improvements!
James

**Comment by ServicePal** [comment]
So, was this issue closed because you have implemented the enhancement (as you are always looking to improve the developer offerings), or was it closed because you have no such plans?

**Comment by johnstan** [comment]
Over a year ago and still waiting for an answer on whether this basic functionality will (in line with EVERY OTHER PAYMENT PROVIDER EVER) be added?
