### ISSUE TITLE
Is the Microphone permission still used (since the 3.0 update)?

### ISSUE THREAD

**Issue by Zyphrax** [sumup/sumup-ios-sdk#59]
Quoted from the README:
> The SumUp SDK requires access to the user's location, Bluetooth peripherals and the device's microphone

I noticed this in the CHANGELOG for version 3.0:
> [REMOVED] Drop support for audio connection to first generation PIN+ devices.

Is the microphone permission still used?
Could you also please explain why the user's location is used?

**Comment by mollidor** [comment]
Hi Zyphrax.

The microphone permission is still needed for audio connection to more recent PIN+ devices (we only dropped support for a legacy audio encoding) and Chip-And-Signature readers.
However the SDK will only ask for microphone access when the merchant logged in uses one of these readers.

The user's location is needed for Anti-Fraud reasons as we need to know where a transaction took place.

I've opened a ticket to improve the SDK readme.

Regards,
Lukas
