### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by viccotr** [sumup/sumup-ios-sdk#61]
Hi, I use SumUp SDK in my app, I was success with binding sdk to xamarin and before CheckoutWithRequest all works correctly but after calling this method I got crash. 

> Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[AppDelegate window]: unrecognized selector sent to instance 0x155bfc00

As I understand from other similar issues the problem connected with ViewController, does it?

**Comment by mollidor** [comment]
Hi @viccotr .

It seems the `fromViewController` is not provided correctly. Can you double check that you pass a view controller _and_ this view controller is indeed the view controller you believe it to be? I'm wondering whether you are trying to present it from a disappearing view controller.

**Comment by viccotr** [comment]
Yes, problem was connected with view controller, thanks. 
May I ask one more thing? All works correctly but test mode is on, I didn't call any test mod on methods, how turn off it?

**Comment by mollidor** [comment]
What do you mean by "test mode"? If you are using a test account we won't charge your card. As soon as you are using a "real" merchant we should start charging the card used. 
Did this answer your question?
