### ISSUE TITLE
ERROR: Error Domain = com.sumup.sdk Code=22 "(null)"

### ISSUE THREAD

**Issue by RameshbabuJaga** [sumup/sumup-ios-sdk#64]
I have checked the documentation and not able to find out the cause. Please help me.

**Comment by Ceroce** [comment]
There's an enum with all the errors declared. If my memories are good, 22 corresponds to "already logged in".

**Comment by RameshbabuJaga** [comment]
Thanks for the update. Let me check and update soon.

**Comment by shagedorn** [comment]
That is indeed the right error code/message. Will close, but feel free to reopen should the code be misleading/wrong.
