### ISSUE TITLE
Crash when get checkout view

### ISSUE THREAD

**Issue by SafiStudio** [sumup/sumup-ios-sdk#65]
I'm trying to use checkout with request method in swift. User is logged up. Application is crashing when checkout view appearing. I get errors:
```
[__NSFrozenArrayM objectAtIndexSafe:]: unrecognized selector sent to instance 0x10921ba10
---
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSFrozenArrayM objectAtIndexSafe:]: unrecognized selector sent to instance 0x10921ba10
```

Here is my sample code showing checkout view:

```
let request = CheckoutRequest(total: 12.00,
                                      title: "Test",
                                      currencyCode: merchantCurrencyCode,
                                      paymentOptions: [.cardReader, .mobilePayment])
request.foreignTransactionID = "your-identifier-12"
SumUpSDK.checkout(with: request, from: self, completion: nil)
```

Any ideas, suggestions on how to fix this?

**Comment by mollidor** [comment]
He Paweł.

Thanks for raising this. We've received this report via email before so I am pretty sure you are into something there. We couldn't reproduce it yet but will keep you posted.

Can you let us know what screen you see last exactly? So you call checkout and which screen appears for you? When exactly does it crash? Is setup presented before the crash?

Thanks,
Lukas

**Comment by mollidor** [comment]
Can you reproduce the crash in one of the sample apps we provide?

**Comment by SafiStudio** [comment]
Hi,

Last screen was with image of SumUp device and "Please set up card terminal" label.
I've just found out what I did wrong. I forgot about point 4 of installation manual:
4. Add -ObjC to "Other Linker Flags" if not yet included

Now it works perfect! ;)

**Comment by mollidor** [comment]
Glad you solved it. Thanks for updating the issue.
