### ISSUE TITLE
Xcode 10 compilation problem

### ISSUE THREAD

**Issue by gduranon** [sumup/sumup-ios-sdk#67]
Hi

Trying to compile my project under Xcode 10 throws the following problem:

ld: warning: directory not found for option '-/Frameworks/SumupSDK.embeddedframework'
ld: library not found for -lstdc++.6.0.9
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Apple documentation specifies that libstdc++ support was removed from iOS 12, and all projects should migrate to libc++ instead.

Do you have plans to support libc++ instead of libstdc++ ?

**Comment by mollidor** [comment]
Hi Gonzalo.

Thanks for raising the issue. We'll look into it and let you know.

Regards,
Lukas

**Comment by mollidor** [comment]
Hi Gonzalo.

I haven't been able to reproduce this using [v3.1](https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.1) of the SumUp SDK and the sample apps provided.

Using the Xcode 10 GM I do get two warnings we shall fix in 3.1.1
> warning: The app icon set "AppIcon" has an unassigned child.

But even when raising the deployment target of the sample apps to iOS 12 I can't see any warning for the C++ standard library.

Can you make sure you are on the latest version of the SumUp SDK? The framework is spelled `SumUpSDK.embeddedframework` with an uppercase `U` .
So maybe this linker warning is the culprit:
> ld: warning: directory not found for option '-/Frameworks/SumupSDK.embeddedframework'

Can you try to reproduce this in the sample apps provided in v3.1 and let us know. We are happy to help.

Regards,
Lukas

**Comment by pikasimo** [comment]
we have problem if i compile for archive or for appstore, if i run to debug o my test device works... can you help me? i add -ObjC to other link flag

**Comment by mollidor** [comment]
Hi there.

Which SDK version are you using? Try the latest 3.4. Also test your integration: https://github.com/sumup/sumup-ios-sdk#test-your-integration

What is the error message you get when trying to archive for App Store?

**Comment by pikasimo** [comment]
hi, the latest sdk present on your link i used... this is error
`
Ld /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/VanigliaPro\ Beta normal armv7  
    cd "/Users/Simone/Desktop/Lavori/prove c mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura"  
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"  
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target armv7-apple-ios8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/BuildProductsPath/Release-iphoneos -L/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/iOrmaBeauty/BixolonLib -L/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura -L/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/iOrmaBeauty -F/Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/BuildProductsPath/Release-iphoneos -F/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/iOrmaBeauty/Resources -F/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/iOrmaBeauty -F/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura -F/Users/Simone/Desktop/Lavori/prove\ c\ mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/SumUpSDK.embeddedframework -filelist /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/VanigliaPro\ Beta.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/VanigliaPro\ Beta_lto.o -Xlinker -final_output -Xlinker /Applications/VanigliaPro\ Beta.app/VanigliaPro\ Beta -fobjc-arc -fobjc-link-runtime -ObjC -framework CoreGraphics -framework AVFoundation -framework EventKit -framework CoreBluetooth -framework CoreText -framework SystemConfiguration -lLWPrintLib -framework AddressBook -framework CFNetwork -framework Accelerate -framework Security -framework QuartzCore -framework ExternalAccessory -lacquisitionstream -framework MobileCoreServices -lSocketRocket -framework ExternalAccessory -licucore -framework MapKit -framework CoreLocation -framework SumUpSDK -framework MapKit -framework AudioToolbox -framework MessageUI -lBXSDK -framework UIKit -framework Foundation -Xlinker -dependency_info -Xlinker /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/VanigliaPro\ Beta_dependency_info.dat -o /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/VanigliaPro\ Beta  
  
..  
..  
..  
  
duplicate symbol '_OBJC_METACLASS_$__SRRunLoopThread' in:  
    /Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/SRWebSocket.o  
    /Users/Simone/Desktop/Lavori/prove c mac/VanigliaPro_beta_xcode5_ios8_beta_gelaterie_ios12_agendaserver_testautolayout_ios13_nochiusura/libSocketRocket.a(SRWebSocket.o)  
ld: 58 duplicate symbols for architecture armv7  
clang: error: linker command failed with exit code 1 (use -v to see invocation)  

`

**Comment by mollidor** [comment]
Hi.

```
duplicate symbol 'OBJC_METACLASS$__SRRunLoopThread' in:
/Users/Simone/Library/Developer/Xcode/DerivedData/vanigliaprobeta-bpcoljlsebektkallekedlwrurip/Build/Intermediates.noindex/ArchiveIntermediates/vanigliapro.temp_caseinsensitive_rename/IntermediateBuildFilesPath/vanigliaprobeta.build/Release-iphoneos/vanigliaprobetaios.build/Objects-normal/armv7/SRWebSocket.o
```

makes me believe there's something else strange in your project setup. Our SDK does not link against `SRWebSocket` so I doubt the culprit is in the SDK integration but somewhere else in your dependencies.
