### ISSUE TITLE
SumUpSDK.setup() should not ask for location permission.

### ISSUE THREAD

**Issue by Ceroce** [sumup/sumup-ios-sdk#71]
`SumUpSDK.setup()` asks the permission to access the user's current location, as stated in its documentation, and as seen in my own experience.
Whereas I do understand the need to locate the user to limit frauds, I think it's a very wrong place to do so.

For instance, we need to call `SumUpSDK.setup()` before calling `SumUpSDK.isLoggedIn`. At this point, we might not even know if the user wants to pay using SumUp, but it will show the Location Permission alert nonetheless.

The location is not needed before a payment is made, so the request to get the permission should only take place in `SumUpSDK.checkout()`. (or let our code do it).

**Comment by mollidor** [comment]
Hi @Ceroce .

Fair point. Until now it's in `setup()` to avoid any mistakes and missing to start acquiring a fix. In our experience acquiring a location might take a while os preferably you do start this early on.

Your point is taken, though. We'll try to add an option to optionally defer asking for permissions to a later stage.

Regards,
Lukas

**Comment by jadeburton-sumup** [comment]
I am going to close this ticket because it is 5 years old. If this issue is pressing we can reopen it.
