### ISSUE TITLE
loginWithToken

### ISSUE THREAD

**Issue by marcosanson** [sumup/sumup-ios-sdk#73]
I made the api post to obtain access_token and then I tried loginWithToken with the access_token I obtained. This is the result:

`
Error Domain=com.sumup.sdk Code=20 "Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-1TL47)" UserInfo={NSLocalizedDescription=Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-1TL47), NSUnderlyingError=0x600002d3db60 {Error Domain=JSONRPCServerError Code=-32001 "Application error" UserInfo={NSLocalizedDescription=Application error, JSONObject={
    code = "-32001";
    data =     {
        message = "Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-1TL47)";
    };
    message = "Application error";
}}}}
`

Please help..

**Comment by omerguen** [comment]
I do have the same Problem, whats is here a solution? Is anybody here?

**Comment by JullianSU** [comment]
Hi @marcosanson @omerguen 

Thank you for getting in touch with us. Would you be able to share some information via email at integration@sumup.com 

Please send me your authentication request and the client_id you are using. 

Many thanks,

**Comment by ugochirico** [comment]
I'm having the same problem right now. Did you get a solution for that issue?

**Comment by Darr598** [comment]
Any update on this ?

**Comment by origamih** [comment]
I'm experiencing the same problem

**Comment by JullianSU** [comment]
Hi Orgamih, 

Thank you for getting in touch with us. Would you be able to share some information via email at integration@sumup.com

Please send me your authentication request and the client_id you are using. It is probably access missing into your account.

Many thanks,

**Comment by juha1604** [comment]
We experienced the same issue.
In our case, this issue was caused by changing the requested scope after we've been already authorised by the user.
It doesn't matter if you add or remove scopes, if the initial scope set differs from you current you will get this problem

One possible solution is to generate new credentials for oauth2

**Comment by mfhaberlach** [comment]
> We experienced the same issue.
> In our case, this issue was caused by changing the requested scope after we've been already authorised by the user.
> It doesn't matter if you add or remove scopes, if the initial scope set differs from you current you will get this problem
> 
> One possible solution is to generate new credentials for oauth2

https://github.com/sumup/sumup-ios-sdk/issues/90

**Comment by zmagyar** [comment]
Is there any solution for this problem? I'm just facing the same ATM.
