### ISSUE TITLE
SumUp SDK error: Internal Server Error (2iqlpvk0ljijl)

### ISSUE THREAD

**Issue by formicheedintorni** [sumup/sumup-ios-sdk#76]
Hi!
I receive the message in object of this issue when I try to create a checkout: I'm implementing the software in a web page for card payment. In a post I found that the problem is generated from disable geolocation but I'm using browser from pc, I enabled geolocation but I had no results.
Thanks,

Mic

**Comment by JullianSU** [comment]
Hi Formicheedintorni, 

Thank you for your message, would you be able to share a bit more on your use case and what you would like to achieve with SumUp SDK? Please contact us at integration@sumup.com. 

Many thanks,

**Comment by formicheedintorni** [comment]
Hi!
I solved: whe I tried to create a checkout into the request I sent  a random email instead the merchant email, so I received "Server Error". I hope that this can help somebody else.

Mic
