### ISSUE TITLE
Bit code support

### ISSUE THREAD

**Issue by ls-david-clerc** [sumup/sumup-ios-sdk#8]
Hi. Do you plan to compile your SDK with the ENABLE_BITCODE setting on? Most of the other SDKs that we are using have support for this.

**Comment by mollidor** [comment]
Hi.

We are planning to support Bitcode as soon as possible. We do rely on a couple of frameworks, that are not Bitcode enabled yet, though. 
Is the lack of Bitcode blocking you at the moment?

Regards,
Lukas

**Comment by dclerc** [comment]
It is not blocking for us but we realized that all the other SDKs have transitioned to Bitcode support and were wondering when your SDK would transition.

Feel free to close this issue when BitCode support is implemented.

**Comment by alvaromb** [comment]
+1!

Would be nice to have bitcode enabled.

**Comment by dclerc** [comment]
We would need this issue to be resolved asap. Apple has started to implement a warning about mixed executables when we upload new binaries.

What we would like to get from you is a clean, bitcode-compatible SDK. If you have older code that does not support bitcode, remove it and let us know the implications (e.g. if some older devices are not supported any longer after the change, we'll inform our clients).

Thank you. You're the last of the SDKs that we integrate with that does not have bitcode support.

**Comment by mollidor** [comment]
Hi @dclerc .

Thanks for bringing this up again. We'll look into it as soon as possible.

**Comment by jhnvz** [comment]
+1

**Comment by quarac** [comment]
This will be great. I'm disabling bitcode in my whole app and frameworks to test the sumup sdk, but for an AppStore version bitcode is required for us.

**Comment by mollidor** [comment]
Hi folks.

We know it has been a long time, let me give you an update.

We are on it. With version 3.0 of the SDK we will drop support for iOS 6/7 which will us allow to rework some internal dependencies. By doing so we will be able to finally support Bitcode and eventually move to a dynamic framework setup. 

Can't give you an ETA just now but it's on our roadmap and we will have something ready in Q4.

Regards,
Lukas

**Comment by mollidor** [comment]
Hi all.

We just published [v3.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.0). Unfortunately we have one dependency left that still doesn't allow us to enable Bitcode. We hope to have a 3.1 early next year that adds Bitcode. Finally.

Regards,
Lukas

**Comment by bartoszstelmaszuk** [comment]
Hi @mollidor,

What is an update for enabled Bitcode in version 3.1? We want to use your SDK in app and it would be a problem if it will still not support Bitcode.

Regards,
Bartosz

**Comment by uddinr** [comment]
hi any update on bit code support?

**Comment by shagedorn** [comment]
Unfortunately, there is no news on this front. We use binary dependencies that have not enabled bitcode yet, nor do we have a guarantee from their vendors that they ever will (although we do ask for it regularly, and we had some hope, as can be seen from this issue's history). These dependencies are required for important hardware integrations and cannot be dropped.

While we are aware this is not ideal, we do not expect the lack of bitcode support to be critically blocking for any integrator, as Apple only requires bitcode for tvOS and watchOS, which we do not support. We are sorry for the incovenience.

**Comment by alexlevy0** [comment]
+1

**Comment by Geoffrey-T** [comment]
Hi Guys,

Since 3 years, any update on this issue ? Nothing planned yet?

Regards,

Geoffrey.

**Comment by Ceroce** [comment]
I'm asking the same question. Maybe it's time to put some real pressure on your vendors. 
It's been three years, and enabling bitcode is not hard.

**Comment by JullianSU** [comment]
Hi Geoffrey, Hi Ceroce, 

Thank you for raising your concern here, what would be the use case to support bitcode? 

Many thanks,

**Comment by Ceroce** [comment]
For now, enabling Bitcode allows our apps to be downloaded quicker. 

However my real concern is that Apple might decide to make Bitcode mandatory to submit to the AppStore. They do enforce this kind of rules regularly.

**Comment by Geoffrey-T** [comment]
Which dependency is problematic to support bitcode on your side ?

**Comment by Crhaj** [comment]
+1 to this. Apple is well known for making recommended things mandatory.

**Comment by 1nvisibleKing** [comment]
+1!
It would be nice to have this issue closed after 5 years!!!

**Comment by Akhila-ramesh** [comment]
Any update on this ?
