### ISSUE TITLE
Attempting to integrate iOS SDK for first time 9.7" iPad iOS 12.3.1

### ISSUE THREAD

**Issue by philatkin** [sumup/sumup-ios-sdk#80]
I see this message on a trap : 

2019-07-16 20:58:55.181849+0100 parishGiving[1913:251831] -[SMPSDKLoginViewController ish_addChildViewController:in:]: unrecognized selector sent to instance 0x119e46e40

when calling 
    [SMPSumUpSDK presentLoginFromViewController:self animated:YES completionBlock:nil ];

Any idea how I can proceed? SetupwithAPIKey returned TRUE,     
[SMPSumUpSDK testSDKIntegration]; worked fine as well.

**Comment by floschliep** [comment]
Hi @philatkin,

can you please double check that you completed the following step of the setup:

> 4. Add -ObjC to "Other Linker Flags" if not yet included.

You can find the "Other Linker Flags" setting in your target's Build Settings.

Thanks,
Florian

**Comment by philatkin** [comment]
You know, I haven’t checked that because the entire project is ObjC so I just assumed I didn’t need to follow up on it. Will check, after an hour at the back of class wearing the Dunce hat. Cheers.

**Comment by philatkin** [comment]
This is a feature request, but please consider it - is there a way to enforce a single email address during initialization, so that once the app is running the SumUp account details cannot be changed? 

This is a REALLY good security feature that iZettle have put into their SDK, but they then missed the next trick, that when the SDK is initialized with an ‘enforced email’ there is still a Logout button available. With an enforced email address, and no means to log out, an unmanned donation terminal running in guided access mode is MUCH more secure, nobody can change the account into which donations are being placed.

If your team would like to get onto the public beta of my app, please let me know and take a look. It is iZettle-only at present but I am getting SumUp support into it for the next release (which will require a bunch of artwork and coding changes, it may be a month or two)

cheers

Phil

**Comment by JullianSU** [comment]
Hi Philtakin, 

Thank you for your feedback, could you please send your request at integration@sumup.com. We will be able to follow from there and find the best solution for your use case. 

Many thanks,

**Comment by floschliep** [comment]
Hi @philatkin - did the linker flag fix this issue? If so, I'll go ahead and close this issue.

**Comment by philatkin** [comment]
Hi

It did, thanks. I am close to having a SumUp version on TestFlight.
