### ISSUE TITLE
SumUp wants the microphone permission if bluetooth permission is not granted

### ISSUE THREAD

**Issue by mfhaberlach** [sumup/sumup-ios-sdk#84]
Hello, we're using the latest SumUp release 3.3 an noticed a strange behavior today.

If we revoke the bluetooth permission from our app and then log in to SumUp, a screen appears which tells me to grant the microphone permission.

When we grant the bluetooth permission and login to SumUp again, the screen did not appear.

That is pretty confusing for the users.

![IMG_A91CC6670227-1](https://user-images.githubusercontent.com/47661501/67389954-f1faeb00-f59b-11e9-8b9c-9fd71dded37a.jpeg)

**Comment by mollidor** [comment]
That is quite confusing indeed, thanks for raising. My hunch is that the account is configured to use our PIN+ reader which - depending on the hardware generation - is able to connect via an audio cable. So when the app lacks BT permissions it will fall back to audio and thus ask for Microphone access. 

But I fully agree it is confusing and the screen is also horribly broken.

**Comment by mollidor** [comment]
One more question: Is this a debug app you are running and is it lacking an icon file? We would have expected to see the app's icon in the last line - and yes, the string format is broken.

**Comment by mfhaberlach** [comment]
Oh sorry, everything is fine with the AppIcon we just blacked it out, just the string format is wrong

**Comment by mollidor** [comment]
Hi.

While not addressing the underlying audio permission issue [v3.4](https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.4) will at least fix the string formatting.

It also addresses important changed to TLS that come with iOS 13.3 so you will want to update to this version at your earliest convenience.

Regards,
Lukas
