### ISSUE TITLE
ITMS-90809: Deprecated API Usage (UIWebView)

### ISSUE THREAD

**Issue by michaelprankl99** [sumup/sumup-ios-sdk#91]
Apple/App Store Connect has identified an issue with the app I delivered.
I got this message from them some days ago:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After checking my app, I found out that this problem is caused by the SumUpSDK (I am using the latest version 3.4). 
I used the command `grep -r "UIWebView" .` to find out where exactly the deprecated API is used as you can see here:
![mac_screenshot](https://user-images.githubusercontent.com/46670585/80957621-d2beff00-8e03-11ea-812f-6b1b46ee7aff.png)

When will this be fixed? Or is there a workaround?

**Comment by cwimberger** [comment]
We've just finished integrating and testing the SumUp SDK and can't submit to the app store now because of that. @mollidor can you help us out here?

**Comment by cwimberger** [comment]
There's already an issue for this: https://github.com/sumup/sumup-ios-sdk/issues/82
