### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by pierceglennie** [sumup/sumup-ios-sdk#94]
It would be great to have support for Swift Package Manage as an alternative to CocoaPods/Carthage, now that it is built into Xcode and supports binary frameworks:

https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by mollidor** [comment]
Hi @pierceglennie .

We just published [v4.0.0-beta.1](https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.0.0-beta.1) . Check the [Migration Guide](https://github.com/sumup/sumup-ios-sdk/blob/develop/MIGRATION.md#sumup-mpos-sdk-400-beta1-migration-guide), integration of the SDK should have become way easier.

Now that we are distributing the SDK as an xcframework we will look into adding support for Swift Package Manager in an upcoming release. 

Kind regards,
Lukas

**Comment by pierceglennie** [comment]
Thanks. Good to see some updates coming through. Will try to migrate in next couple weeks and let you know if I face any issues.

**Comment by mollidor** [comment]
Hey @pierceglennie 

We published [v4.0.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.0.0). We've outlined support for Swift PM in the [README](https://github.com/sumup/sumup-ios-sdk/blob/master/README.md#integration-via-swift-pm). It's not seamless yet but we hope for [SR-13343](https://bugs.swift.org/browse/SR-13343) to be addressed soon.

Best,
Lukas

**Comment by pierceglennie** [comment]
@mollidor Just to let you know I upgraded to v4.0.0 and migrated to Swift PM. I've not been able to test everyone yet but it seems to have gone smoothly and it's meant I'm no longer getting any warnings on build (which the old SumUp SDK gave me). Thanks for your efforts

**Comment by mollidor** [comment]
That's great to hear 🎉 . Thanks a lot for coming back to us, much appreciated.
