### ISSUE TITLE
Issue shows up "SumUp only works when you are online..." when trying to login

### ISSUE THREAD

**Issue by MaxenceSchoonians** [sumup/sumup-ios-sdk#99]
Hi,

We currently have an iPad application for a customer who worked in the retail area here in Belgium.
The application was developed approx. 18 months ago, and everything was working fine.

We now have an issue when trying to login with the SumUp form. The message we get from the form is: "SumUp only works when you are online. please check your connection and try again." The issue is occurring by testing on the simulator and of course on a real iPad.

Of course we checked our connection and everything is working fine. We also checked our account detail (login/password) and they are working. We tested our credentials directly through the website https://me.sumup.com/fr-be/login/ and also thanks to your demo code downloaded from Github and they work fine.

We verified that the bundle IDs are matching between our profile in the website and the application. We also tested our API key into your demo scene and it worked.

Of course we also tried to upgrade the code of our app to use the latest SumUpSDK version but then we have another strange issue stating that our credentials are not correct. Same by starting a fresh new project with the latest SumUpSDK version and even by following each steps of the tutorial on Github.

To be clear, we are unable to implement SumUpSDK by ourselves, only the demo code seems to be working but in the end we want it to be implemented into our application of course ;)

Since nothing had changed in our code, there must be something that changed "under the hood" at your side. Do you have an idea of how can we fix this issue ?

Thanks by advance.

Our development setup:

Xcode 11.6
macOS Catalina 10.15.5
SumUpSDK 3.1

<img width="907" alt="Screenshot 2020-08-28 at 11 46 12" src="https://user-images.githubusercontent.com/6805689/91550347-b1d96700-e928-11ea-8d29-3919701dfb1e.png">

**Comment by floschliep** [comment]
Hi @MaxenceSchoonians,

version 3.1 of our SDK is quite old (2 years). Please update to a newer version (preferably the latest), they will work.

Best,
Florian

**Comment by mollidor** [comment]
Hi @MaxenceSchoonians 

we just published [v4.0.0-beta.1](https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.0.0-beta.1). Check the Migration Guide, integration of the SDK should have become way easier.

Please double check that your app's bundle identifier matches the bundle identifier(s) you have added to your affiliate key.

If the problem persists, feel free to get in touch with integration@sumup.com and ask them to forward to me.

Kind regards,
Lukas
